/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBInteractionPassThroughView.h"


__attribute__((visibility("hidden")))
@interface _SBAnimatableCorneredView : SBInteractionPassThroughView {
}
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

