/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class _SBFVibrantSettings;

@protocol _SBFVibrantView <NSObject>
@property(retain, nonatomic) _SBFVibrantSettings* vibrantSettings;
-(void)setBackgroundView:(id)view;
@end

