/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@protocol _SBFakeBlurObserver;

@protocol _SBFakeBlur <NSObject>
@property(assign, nonatomic) id<_SBFakeBlurObserver> observer;
-(int)effectiveStyle;
-(void)requestStyle:(int)style;
@end

