/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconZoomAnimator.h"
#import "SpringBoard-Structs.h"
#import "SBIconListLayoutDelegate.h"

@class SBFloatyFolderView, SBFolderZoomSettings, SBFolderIconView;

__attribute__((visibility("hidden")))
@interface _SBInnerFolderIconZoomAnimator : SBIconZoomAnimator <SBIconListLayoutDelegate> {
	SBFloatyFolderView* _folderView;
	SBFolderIconView* _folderIconView;
	CGAffineTransform _folderIconViewScaleTransform;
}
@property(retain, nonatomic) SBFolderZoomSettings* settings;
-(void)_calculateZoomedOffset:(CGPoint*)offset scale:(float*)scale forIcon:(id)icon withView:(id)view;
-(void)_applyFolderFadeForZoomFraction:(float)zoomFraction;
-(void)_applyIconTransformForZoomFraction:(float)zoomFraction;
-(void)_applyIconCrossfadeForZoomFraction:(float)zoomFraction;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController iconView:(id)view iconZoomScale:(float)scale;
@end

