/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "_SBIconProgressStateTransition.h"


__attribute__((visibility("hidden")))
@interface _SBIconProgressWaitingLoadingStateTransition : _SBIconProgressStateTransition {
}
-(void)_updateView:(id)view;
@end

