/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol _SBIconWallpaperColorClient <NSObject>
@property(assign, getter=isBlurring) BOOL blurring;
-(void)setWallpaperColor:(CGColorRef)color phase:(CGSize)phase;
-(BOOL)wantsBlur:(id)blur;
-(CGRect)wallpaperRelativeBounds;
@end

