/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _SBRemoteAlertHostViewControllerDelegate <NSObject>
-(void)remoteAlertDidTerminateWithError:(id)remoteAlert;
-(void)remoteAlertWantsToAllowBanners:(BOOL)allowBanners;
@end

