/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIRemoteAlertHostInterface.h"

@class NSString;
@protocol _SBRemoteAlertHostViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface _SBRemoteAlertHostViewController : XXUnknownSuperclass <SBUIRemoteAlertHostInterface> {
	id<_SBRemoteAlertHostViewControllerDelegate> _delegate;
	NSString* _serviceClassName;
}
@property(copy, nonatomic) NSString* serviceClassName;
@property(assign, nonatomic) id<_SBRemoteAlertHostViewControllerDelegate> delegate;
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)viewServiceDidTerminateWithError:(id)viewService;
-(void)dismiss;
-(void)setAllowsBanners:(BOOL)banners;
-(id)description;
@end

