/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol _SBUIWidgetViewController_Host_IPC
-(void)__invalidatePreferredViewSize;
-(void)__requestLaunchOfURL:(id)url;
-(void)__requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context replyHandler:(id)handler;
@end

