/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol _SBUIWidgetViewController_Remote_IPC
-(void)__hostDidDismiss;
-(void)__hostWillDismiss;
-(void)__hostDidPresent;
-(void)__hostWillPresent;
-(void)__requestPreferredViewSizeWithReplyHandler:(id)replyHandler;
-(void)__setWidgetIdiom:(int)idiom;
-(void)__setWidgetIdentifier:(id)identifier;
@end

