/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _SBUIWidgetHost <NSObject>
-(void)invalidatePreferredViewSize;
-(void)requestLaunchOfURL:(id)url;
-(void)requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
@end

