/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "_SBUIWidgetViewController_Host_IPC.h"

@class SBWidgetViewControllerHost;

__attribute__((visibility("hidden")))
@interface _SBWidgetViewControllerHost_Proxy : XXUnknownSuperclass <_SBUIWidgetViewController_Host_IPC> {
	SBWidgetViewControllerHost* _managingHost;
}
@property(assign, nonatomic) SBWidgetViewControllerHost* managingHost;
+(id)exportedInterface;
+(id)serviceViewControllerInterface;
-(void)__invalidatePreferredViewSize;
-(void)__requestLaunchOfURL:(id)url;
-(void)__requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context replyHandler:(id)handler;
-(void)_hostDidDismiss;
-(void)_hostWillDismiss;
-(void)_hostDidPresent;
-(void)_hostWillPresent;
-(void)_requestServicePreferredViewSizeWithReplyHandler:(id)replyHandler;
-(void)_setWidgetIdiom:(int)idiom;
-(void)_setWidgetIdentifier:(id)identifier;
@end

