/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol _UIDynamicReferenceSystem <NSObject>
-(CGRect)bounds;
@optional
-(CGPoint)convertPoint:(CGPoint)point fromView:(id)view;
-(CGPoint)convertPoint:(CGPoint)point toView:(id)view;
@end

