/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol _UIGlintyStringViewDelegate
-(void)glintyFadeOutAnimationDidStop;
-(void)glintyFadeInAnimationDidStop;
-(void)glintyAnimationDidStop;
-(void)glintyAnimationDidStart;
@end

