/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _UISettingsKeyObserver <NSObject>
-(void)settings:(id)settings changedValueForKey:(id)key;
@end

