/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _UIScreenEdgePanRecognizerDelegate <NSObject>
@optional
-(void)screenEdgePanRecognizerStateDidChange:(id)screenEdgePanRecognizerState;
@end

