/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _UISettingsKeyPathObserver <NSObject>
-(void)settings:(id)settings changedValueForKeyPath:(id)keyPath;
@end

