/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AVExternalDeviceDelegate <NSObject>
@optional
-(void)siriRequestedWithAction:(int)action;
-(void)iOSUIRequestedForApplicationURL:(id)applicationURL;
@end

