/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BBSectionIdentity <NSObject>
-(id)sectionIdentifier;
@optional
-(id)sectionIconData;
-(id)sectionIcon;
-(id)sectionDisplayName;
-(id)defaultSectionInfo;
@end

