/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MPAVRoutingControllerDelegate <NSObject>
@optional
-(void)routingController:(id)controller didFailToPickRouteWithError:(id)error;
-(void)routingControllerAvailableRoutesDidChange:(id)routingControllerAvailableRoutes;
@end

