/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMapTable, NSHashTable;

__attribute__((visibility("hidden")))
@interface SBActivationContext : XXUnknownSuperclass <NSCopying> {
	NSMapTable* _displayValues;
	NSMapTable* _activationValues;
	NSMapTable* _deactivationValues;
	NSHashTable* _displayFlags;
	NSHashTable* _activationFlags;
	NSHashTable* _deactivationFlags;
}
@property(copy, nonatomic) NSHashTable* deactivationFlags;
@property(copy, nonatomic) NSMapTable* deactivationValues;
@property(copy, nonatomic) NSHashTable* activationFlags;
@property(copy, nonatomic) NSMapTable* activationValues;
@property(copy, nonatomic) NSHashTable* displayFlags;
@property(copy, nonatomic) NSMapTable* displayValues;
+(id)_descriptionForFlags:(id)flags values:(id)values withNameForSettingFunction:(/*function-pointer*/ void*)settingFunction;
+(id)descriptionForDeactivationFlags:(id)deactivationFlags values:(id)values;
+(id)descriptionForActivationFlags:(id)activationFlags values:(id)values;
+(id)descriptionForDisplayFlags:(id)displayFlags values:(id)values;
+(id)newFlagTable;
+(id)newValueTable;
+(id)contextFromDisplay:(id)display;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(BOOL)deactivationFlag:(unsigned)flag;
-(id)deactivationValue:(unsigned)value;
-(void)setDeactivationSetting:(unsigned)setting value:(id)value;
-(void)setDeactivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDeactivationSettings;
-(void)applyActivationSettingsToDisplay:(id)display;
-(BOOL)activationFlag:(unsigned)flag;
-(id)activationValue:(unsigned)value;
-(void)setActivationSetting:(unsigned)setting value:(id)value;
-(void)setActivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearActivationSettings;
-(BOOL)displayFlag:(unsigned)flag;
-(id)displayValue:(unsigned)value;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithDisplay:(id)display;
@end

