/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAlertDelegate <NSObject>
-(void)alertIsReadyToBeRemovedFromView:(id)view;
-(void)alertIsReadyToBeDeactivated:(id)beDeactivated;
-(void)alert:(id)alert requestsBackgroundStyleChangeWithAnimationFactory:(id)animationFactory;
@end

