/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@protocol SBAlertManagerObserver;

__attribute__((visibility("hidden")))
@interface SBAlertManagerObserverWrapper : XXUnknownSuperclass {
	id<SBAlertManagerObserver> _observer;
	XXStruct_scX9uA _flags;
}
-(id)initWithObserver:(id)observer flags:(XXStruct_scX9uA)flags;
@end

