/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface SBAlertAdapter : SBAlert {
	UIViewController* _effectiveViewController;
}
@property(retain) id display;
@property(readonly, retain) UIViewController* effectiveViewController;
-(id)description;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)alertWindow:(id)window resizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)setView:(id)view;
-(void)dealloc;
-(id)initWithViewController:(id)viewController;
@end

