/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAlertManagerDelegate <NSObject>
@optional
-(id)alertManager:(id)manager newAlertWindowForLockAlerts:(BOOL)lockAlerts;
-(BOOL)alertManager:(id)manager shouldDeactivateDismissedAlert:(id)alert;
@end

