/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAlertObserver <NSObject>
@optional
-(void)alertBannerSuppressionChanged:(id)changed;
@end

