/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherService : XXUnknownSuperclass {
	NSString* _bundleIdentifier;
	NSString* _viewServiceClassName;
}
@property(copy, nonatomic) NSString* viewServiceClassName;
@property(copy, nonatomic) NSString* bundleIdentifier;
+(id)switcherServiceWithName:(id)name viewServiceClassName:(id)name2;
-(id)identifier;
-(void)dealloc;
@end

