/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBAppSliderControllerDelegate
-(void)appSwitcherNeedsToReload:(id)reload;
-(void)appSwitcherWantsToDismissImmediately:(id)dismissImmediately;
-(void)appSwitcher:(id)switcher wantsToActivateApplication:(id)activateApplication;
@end

