/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFileLogger.h"


__attribute__((visibility("hidden")))
@interface SBAppInstallationLogger : SBFileLogger {
	BOOL _enabled;
}
@property(readonly, assign, getter=isEnabled) BOOL enabled;
-(void)reloadFromDefaults;
-(BOOL)includeConsole;
-(id)name;
@end

