/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;

@protocol SBApplicationTerminationAssertion <NSObject>
@property(readonly, assign, nonatomic) unsigned char reason;
@property(readonly, assign, nonatomic) NSString* displayId;
@end

