/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBNewsstandItemIconImageView.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconImageView : SBNewsstandItemIconImageView {
}
+(int)_defaultIconFormat;
@end

