/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAppSwitcherPageContentView.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBAppSliderServiceCellView : XXUnknownSuperclass <SBAppSwitcherPageContentView> {
	int _orientation;
}
@property(assign, nonatomic) int orientation;
-(CGSize)sizeThatFits:(CGSize)fits;
@end

