/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "_SBUISwitcherPageHostInterface.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherPageServiceRemoteViewController : XXUnknownSuperclass <_SBUISwitcherPageHostInterface> {
}
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

