/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNewsstandItemIconView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconView {
}
+(float)_labelHeight;
+(int)_defaultIconFormat;
-(float)_labelVerticalOffset;
-(CGRect)_frameForUpdatedMarkWithLabelFrame:(CGRect)labelFrame;
-(CGRect)_frameForLabel;
-(id)initWithFrame:(CGRect)frame;
@end

