/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAppSwitcherPageContentView <NSObject>
@property(assign) int orientation;
@optional
-(void)unsimplifyAfterMotion;
-(void)simplifyForMotion;
-(void)respondToBecomingInvisibleIfNecessary;
-(void)prepareToBecomeVisibleIfNecessary;
@end

