/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIScrollViewDelegate.h"

@class SBStopScrollingGestureRecognizer, UITapGestureRecognizer, NSMutableArray, SBAppSliderScrollView;
@protocol SBAppSliderScrollingViewDelegate;

__attribute__((visibility("hidden")))
@interface SBAppSliderScrollingViewController : XXUnknownSuperclass <UIScrollViewDelegate> {
	NSMutableArray* _items;
	SBAppSliderScrollView* _scrollView;
	BOOL _dragMaster;
	BOOL _preventScroll;
	UITapGestureRecognizer* _tapGesture;
	SBStopScrollingGestureRecognizer* _stopScrollingGesture;
	int _layoutOrientation;
	id _scrollDoneBlock;
	BOOL _isMoving;
	id<SBAppSliderScrollingViewDelegate> _delegate;
}
@property(assign, nonatomic) float normalizedOffset;
@property(assign, nonatomic) id<SBAppSliderScrollingViewDelegate> delegate;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)scrollViewWillEndDragging:(id)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint*)offset;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)_fireAndCleanupScrollCompleteBlockIfNecessary;
-(void)_setContentOffset:(CGPoint)offset animated:(BOOL)animated;
-(void)_enableScrolling;
-(void)_disableScrolling;
-(BOOL)_isIndexVisible:(unsigned)visible withSidePadding:(float)sidePadding;
-(void)_updateVisiblePageViews;
-(void)_layout;
-(void)_layoutIndexContainer:(unsigned)container;
-(void)_generateViewIndexIfNecessary:(unsigned)necessary;
-(CGRect)_naturalScrollViewFrame;
-(CGPoint)_centerOfIndex:(unsigned)index;
-(float)_distanceBetweenCenters;
-(void)_handleStopGesture:(id)gesture;
-(void)_handleTapGesture:(id)gesture;
-(void)removeIndex:(unsigned)index duration:(double)duration;
-(void)cancelPossibleRemovalOfIndex:(unsigned)index;
-(void)reloadInOrientation:(int)orientation;
-(float)_halfWidth;
-(void)viewDidDisappear:(BOOL)view;
-(void)loadView;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(float)preferredHeightForOrientation:(int)orientation;
-(void)switcherWasDismissed:(BOOL)dismissed;
-(NSRange)visibleItems;
-(BOOL)isScrolling;
-(BOOL)_isAnyScrollContainerScrolling;
-(id)pageViewForIndex:(unsigned)index;
-(unsigned)currentPage;
-(void)_setScrollingDoneBlock:(id)block;
-(BOOL)isIndexVisible:(unsigned)visible;
-(unsigned)settledIndexForNormalizedOffset:(inout float*)normalizedOffset andXVelocity:(float)velocity;
-(float)normalizedOffsetForOffset:(float)offset andXVelocity:(float)velocity;
-(float)normalizedOffsetOfIndex:(unsigned)index;
-(void)setOffsetToIndex:(unsigned)index animated:(BOOL)animated completion:(id)completion;
-(void)setOffsetToIndex:(unsigned)index animated:(BOOL)animated;
-(void)cancelScrolling;
-(float)_maxXOffset;
-(void)dealloc;
-(id)init;
@end

