/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationTerminationAssertion.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBApplicationTerminationAssertionManager;

__attribute__((visibility("hidden")))
@interface SBApplicationTerminationAssertionImpl : XXUnknownSuperclass <SBApplicationTerminationAssertion> {
	NSString* _displayId;
	unsigned char _reason;
	SBApplicationTerminationAssertionManager* _manager;
}
@property(readonly, assign, nonatomic) unsigned char reason;
@property(readonly, assign, nonatomic) NSString* displayId;
-(id)description;
-(void)dealloc;
-(id)initWithDisplayId:(id)displayId reason:(unsigned char)reason manager:(id)manager;
@end

