/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAppSliderContainerDelegate <NSObject>
-(void)appSliderContainer:(id)container movedToWindow:(id)window;
@end

