/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBApplicationRestrictionDataSource <NSObject>
-(id)allApplications;
-(id)applicationWithDisplayIdentifier:(id)displayIdentifier;
@end

