/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppSwitcherServices;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherServiceManager : XXUnknownSuperclass {
	SBAppSwitcherServices* _services;
}
+(id)sharedInstance;
-(id)registeredServicesSnapshot;
-(void)unregisterService:(id)service;
-(void)registerService:(id)service;
-(void)dealloc;
@end

