/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWindow.h"


__attribute__((visibility("hidden")))
@interface SBAppWindow : SBWindow {
}
+(CGRect)constrainFrameToScreen:(CGRect)screen;
@end

