/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"


__attribute__((visibility("hidden")))
@interface SBAppSliderIconView : SBIconView {
}
+(float)_labelHeight;
+(CGSize)maxLabelSize;
-(float)_labelVerticalOffset;
@end

