/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWindow.h"

@class SBAssistantRootViewController;

__attribute__((visibility("hidden")))
@interface SBAssistantWindow : SBWindow {
}
@property(readonly, assign, nonatomic) SBAssistantRootViewController* assistantRootViewController;
-(BOOL)isOpaque;
-(void)dealloc;
-(id)initWithScreen:(id)screen jailBehavior:(int)behavior;
@end

