/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSTimer;

__attribute__((visibility("hidden")))
@interface SBBacklightController : XXUnknownSuperclass {
	double _minimumLockIdleTime;
	NSTimer* _autoLockTimer;
	double _lastTimeIdleCausedDim;
	double _nextLockDurationAfterDim;
	unsigned _disableAutoDimming : 1;
	unsigned _lockScreenCameraWantsIdleTimerDisabled : 1;
	NSMutableSet* _idleTimerDisabledReasons;
	NSMutableSet* _spuriousScreenUndimmingAssertions;
	BOOL _isPendingScreenUnblankAfterCACommit;
	BOOL _undimmedForBulletinSinceLastUserEvent;
	BOOL _allowIdleTimerToBeReset;
}
@property(readonly, assign, nonatomic) BOOL screenIsOff;
@property(readonly, assign, nonatomic) BOOL isPendingScreenUnblankAfterCACommit;
@property(readonly, retain) NSMutableSet* idleTimerDisabledReasons;
+(BOOL)deviceSupportsBacklightRamping;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNeeded:(BOOL)needed;
-(void)preventIdleSleepForNumberOfSeconds:(float)seconds;
-(void)preventIdleSleep;
-(void)allowIdleSleep;
-(void)_startAllowingIdleTimer;
-(void)_requestedUserEventNotificationOccurred;
-(void)_userEventPresenceTimerExpired;
-(void)_userEventOccurred;
-(void)_userEventsDidIdle;
-(void)_lockScreenDimTimerFired;
-(void)_didIdle;
-(void)_autoLockTimerFired:(id)fired;
-(void)_startFadeOutAnimationIfNecessary;
-(BOOL)_lockScreenWantsUserEventNotifications;
-(void)removeSpuriousScreenUndimmingAssertion:(id)assertion;
-(void)addSpuriousScreenUndimmingAssertion:(id)assertion;
-(void)autoLockPrefsChanged;
-(void)animateBacklightToFactor:(float)factor duration:(double)duration source:(int)source completion:(id)completion;
-(void)setBacklightFactor:(float)factor source:(int)source;
-(BOOL)shouldTurnOnScreenForBacklightSource:(int)backlightSource;
-(void)setBacklightFactorPending:(float)pending;
-(void)_deferredScreenUnblankDone;
-(void)turnOnScreenFullyWithBacklightSource:(int)backlightSource;
-(void)setIdleTimerDisabled:(BOOL)disabled forReason:(id)reason;
-(void)setIdleTimerDisabled:(BOOL)disabled;
-(double)defaultLockScreenDimIntervalWhenNotificationsPresent;
-(double)defaultLockScreenDimInterval;
-(void)_resetLockScreenIdleTimerWithDuration:(double)duration mode:(int)mode;
-(void)resetLockScreenIdleTimerWithDuration:(double)duration;
-(void)resetLockScreenIdleTimer;
-(void)cancelLockScreenIdleTimer;
-(double)_currentLockScreenIdleTimerInterval;
-(void)_resetIdleTimerAndUndim:(BOOL)undim source:(int)source;
-(void)resetIdleTimerAndUndimForBulletin;
-(void)resetIdleTimerAndUndim:(BOOL)undim;
-(void)_undimFromSource:(int)source;
-(double)_nextLockTimeDuration;
-(double)_nextIdleTimeDuration;
-(void)clearIdleTimer;
-(void)restoreBacklightFactorForProx;
-(void)setBacklightFactorToZeroForProx;
-(void)_cancelSetBacklightFactorToZeroAfterDelay;
-(void)_setBacklightFactorToZeroForProx;
-(void)_clearAutoLockTimer;
-(id)init;
@end

