/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUIBannerView.h"
#import "SBVibrantBannerView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class _UIBackdropView, UIImage, UIImageView, SBUIBannerContext, UIView, SBBannerViewCallbackManager;

__attribute__((visibility("hidden")))
@interface SBBannerContextView : XXUnknownSuperclass <SBUIBannerView, SBVibrantBannerView> {
	UIEdgeInsets _clippingInsets;
	UIView* _clippingView;
	SBUIBannerContext* _context;
	UIView<SBUIBannerView>* _contentView;
	SBBannerViewCallbackManager* _callbacks;
	SBBannerViewCallbackManager* _wrapperCallbacks;
	_UIBackdropView* _backdropView;
	UIImageView* _backgroundImageView;
	BOOL _isDismissing;
	struct {
		unsigned delegateOverrideRequester : 1;
		unsigned delegateShouldEnableContextHostingForRequester : 1;
	} _contentViewFlags;
}
@property(readonly, assign, nonatomic, getter=isDismissing) BOOL dismissing;
@property(retain, nonatomic) UIImage* backgroundImage;
@property(readonly, assign, nonatomic) _UIBackdropView* backdrop;
@property(assign, nonatomic) UIEdgeInsets clippingInsets;
+(id)defaultColorForElement:(int)element;
-(id)bannerContext;
-(void)layoutSubviews;
-(CGRect)_frameInClippingViewForFrame:(CGRect)frame;
-(void)noteDidDismissWithReason:(int)note;
-(void)noteWillDismissWithReason:(int)note;
-(void)noteDidAppear;
-(void)noteWillAppear;
-(void)setColor:(id)color forElement:(int)element;
-(id)colorForElement:(int)element;
-(id)_vibrantContentView;
-(id)defaultColorForElement:(int)element;
-(void)setBannerContext:(id)context withReplaceReason:(int)replaceReason;
-(CGRect)_contentFrame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

