/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBItemInfo.h"

@class SBBulletinListSection, NSString;

__attribute__((visibility("hidden")))
@interface SBBBSectionInfo : SBBBItemInfo {
	int _sectionCategory;
}
@property(readonly, assign, nonatomic) NSString* listSectionIdentifier;
@property(readonly, assign, nonatomic) SBBulletinListSection* representedListSection;
@property(readonly, assign, nonatomic, getter=isWidgetSection) BOOL widgetSection;
@property(readonly, assign, nonatomic) int sectionCategory;
-(id)identifier;
@end

