/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBBBInfoOperation : XXUnknownSuperclass {
	id _operand;
}
@property(readonly, assign, nonatomic) id operand;
+(id)operationWithOperand:(id)operand;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithOperand:(id)operand;
@end

