/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBBBulletinInfo.h"

@class SBWidgetViewControllerHost, NSString;

__attribute__((visibility("hidden")))
@interface SBBBWidgetBulletinInfo : SBBBBulletinInfo {
	NSString* _identifier;
	CGSize _preferredViewSize;
	BOOL _visible;
	struct {
		unsigned _didFetchDisplayName : 1;
	} _widgetBulletinInfoFlags;
}
@property(assign, nonatomic) CGSize preferredViewSize;
@property(readonly, assign, nonatomic) SBWidgetViewControllerHost* representedWidget;
@property(readonly, retain) NSString* identifier;
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(Class)reusableViewClass;
-(id)originalSectionIdentifier;
-(id)widgetIdentifier;
-(id)representedBulletin;
-(void)dealloc;
@end

