/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBItemInfo.h"

@class BBBulletin, NSString;

__attribute__((visibility("hidden")))
@interface SBBBBulletinInfo : SBBBItemInfo {
}
@property(readonly, assign, nonatomic) BBBulletin* representedBulletin;
@property(readonly, assign, nonatomic) NSString* originalSectionIdentifier;
-(id)identifier;
@end

