/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "_UIDynamicReferenceSystem.h"


__attribute__((visibility("hidden")))
@interface SBBouncingSystem : XXUnknownSuperclass <_UIDynamicReferenceSystem> {
	CGRect _bounds;
}
@property(assign) CGRect bounds;
@end

