/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"

@class SBBookmark;

__attribute__((visibility("hidden")))
@interface SBBookmarkIcon : SBLeafIcon {
	SBBookmark* _bookmark;
}
@property(retain, nonatomic) SBBookmark* bookmark;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(id)webClip;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithBookmark:(id)bookmark;
@end

