/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDefaultBannerViewSource.h"

@class NSArray, UIImage, SBUISound, BBBulletin, BBObserver;

__attribute__((visibility("hidden")))
@interface SBBulletinBannerItem : XXUnknownSuperclass <SBDefaultBannerViewSource> {
	BBBulletin* _seedBulletin;
	BBObserver* _observer;
	NSArray* _additionalBulletins;
	UIImage* _iconImage;
	SBUISound* _sound;
}
@property(readonly, retain) BBBulletin* seedBulletin;
@property(readonly, retain) NSArray* additionalBulletins;
@property(readonly, retain) UIImage* iconImage;
@property(readonly, retain) SBUISound* sound;
+(id)itemWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
+(id)itemWithBulletin:(id)bulletin andObserver:(id)observer;
-(BOOL)overridesQuietMode;
-(BOOL)isCritical;
-(BOOL)inertWhenLocked;
-(BOOL)isVIP;
-(id)attachmentImage;
-(id)attachmentText;
-(id)sourceDate;
-(id)message;
-(id)title;
-(id)pullDownNotification;
-(BOOL)canShowInAssistant;
-(id)sortDate;
-(id)action;
-(void)_setSound;
-(unsigned)accessoryStyle;
-(id)_appName;
-(void)dealloc;
-(id)_initWithSeedBulletin:(id)seedBulletin additionalBulletins:(id)bulletins andObserver:(id)observer;
@end

