/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDefaultDateLabel.h"


__attribute__((visibility("hidden")))
@interface SBBulletinTimerEndDateLabel : SBDefaultDateLabel {
}
-(id)constructLabelString;
@end

