/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDosidoAnimator.h"


__attribute__((visibility("hidden")))
@interface SBCarDosidoAnimator : SBDosidoAnimator {
}
-(void)_doRealDosido:(id)dosido withSpacingBetween:(float)spacingBetween completion:(id)completion;
@end

