/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBCCSettingUnavailableAlertItem : XXUnknownSuperclass {
	int _setting;
}
@property(assign, nonatomic) int setting;
+(id)alertStringForSetting:(int)setting;
+(BOOL)presentAlertItemForSetting:(int)setting;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

