/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBCenterAppZoomSettings.h"


__attribute__((visibility("hidden")))
@interface SBCenterAppSuspendSettings : SBCenterAppZoomSettings {
}
-(void)setDefaultValues;
@end

