/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "_SBFVibrantView.h"

@class UIView, _SBFVibrantSettings, UIColor;

__attribute__((visibility("hidden")))
@interface SBChevronView : XXUnknownSuperclass <_SBFVibrantView> {
	UIView* _leftGrabberView;
	UIView* _rightGrabberView;
	double _animationDuration;
	int _state;
	UIColor* _color;
	float _alphaComponent;
	_SBFVibrantSettings* _vibrantSettings;
	UIView* _tintView;
	UIView* _backgroundView;
	BOOL _unified;
	UIView* _alphaContainerView;
}
@property(retain, nonatomic) _SBFVibrantSettings* vibrantSettings;
@property(retain, nonatomic) UIColor* color;
@property(assign, nonatomic) int state;
@property(assign, nonatomic) double animationDuration;
-(void)setBackgroundView:(id)view;
-(id)description;
-(void)setState:(int)state animated:(BOOL)animated;
-(BOOL)_setUnified:(BOOL)unified;
-(BOOL)_setState:(int)state;
-(void)layoutSubviews;
-(void)_layoutGrabberView:(id)view forState:(int)state;
-(CGRect)_frameForGrabberView:(id)grabberView forState:(int)state unified:(BOOL)unified;
-(CGAffineTransform)_transformForGrabberView:(id)grabberView forState:(int)state;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(id)initWithColor:(id)color;
-(id)initWithFrame:(CGRect)frame;
@end

