/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BBRemoteDataProvider.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BBDataProviderProxy, UILocalNotification, NSDate, NSTimer, BBBulletinRequest;

__attribute__((visibility("hidden")))
@interface SBClockDataProvider : XXUnknownSuperclass <BBRemoteDataProvider> {
	NSTimer* _alarmUpdateTimer;
	BBDataProviderProxy* _dataProviderProxy;
	UILocalNotification* _nextAlarmForToday;
	BBBulletinRequest* _nextTodayAlarmBulletin;
	UILocalNotification* _firstAlarmForTomorrow;
	NSDate* _nextTomorrowFireDate;
	BBBulletinRequest* _nextTomorrowAlarmBulletin;
}
+(id)sharedInstance;
-(id)sortDescriptors;
-(id)bulletinsWithRequestParameters:(id)requestParameters lastCleared:(id)cleared;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(id)defaultSectionInfo;
-(id)sectionIdentifier;
-(id)_alarmMessageForNotification:(id)notification withSingleAlarmFormat:(BOOL)singleAlarmFormat;
-(void)_publishAlarmsWithScheduledNotifications:(id)scheduledNotifications;
-(void)_calculateNextTomorrowAlarmAndBulletinWithScheduledNotifications:(id)scheduledNotifications;
-(void)_calculateNextTodayAlarmAndBulletinWithScheduledNotifications:(id)scheduledNotifications;
-(id)_nextAlarmForFeed:(unsigned)feed withNotifications:(id)notifications;
-(void)_snoozedAlarmRefired:(id)refired;
-(id)_bulletinRequestForSnoozedAlarm:(id)snoozedAlarm;
-(void)_handleAlarmSnoozedNotification:(id)notification;
-(id)_bulletinRequestForTimerNotification:(id)timerNotification;
-(void)_publishTimerInScheduledNotifications:(id)scheduledNotifications;
-(id)_scheduledNotifications;
-(void)_handleClockNotificationUpdate:(id)update;
-(void)dealloc;
-(id)init;
@end

