/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBApplicationIcon.h"


__attribute__((visibility("hidden")))
@interface SBClockApplicationIcon : SBApplicationIcon {
}
-(Class)iconImageViewClassForLocation:(int)location;
@end

