/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"

@class SBControlCenterContentContainerView, SBChevronView, UIView;

__attribute__((visibility("hidden")))
@interface SBControlCenterContainerView : XXUnknownSuperclass <SBControlCenterObserver> {
	UIView* _darkeningView;
	float _revealPercentage;
	float _previousBGColorAlpha;
	SBChevronView* _chevronToTrack;
	BOOL _animatingDynamically;
	UIView* _dynamicsContainerView;
	SBControlCenterContentContainerView* _contentContainerView;
}
@property(assign, nonatomic) BOOL animatingDynamically;
@property(assign, nonatomic) float revealPercentage;
@property(readonly, assign, nonatomic) SBControlCenterContentContainerView* contentContainerView;
@property(readonly, assign, nonatomic) UIView* dynamicsContainerView;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillFinishTransitionOpen:(BOOL)controlCenter withDuration:(double)duration;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)updateBackgroundSettings:(id)settings;
-(void)abortAnimatedTransition;
-(id)_contentChevronView;
-(id)_currentBGColor;
-(void)_updateContentFrame;
-(void)_updateDarkeningFrame;
-(void)trackChevronView:(id)view;
-(void)setContentHeight:(float)height;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

