/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBOffscreenSwipeGestureRecognizer.h"


__attribute__((visibility("hidden")))
@interface SBControlCenterSwipeGestureRecognizer : SBOffscreenSwipeGestureRecognizer {
}
-(id)initForOffscreenEdge:(unsigned)offscreenEdge;
@end

