/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"

@class SBControlCenterContentView, UIView, _UIBackdropView;

__attribute__((visibility("hidden")))
@interface SBControlCenterContentContainerView : XXUnknownSuperclass <SBControlCenterObserver> {
	UIView* _accessibilityBackgroundView;
	_UIBackdropView* _backdropView;
	SBControlCenterContentView* _contentView;
	float _contentHeight;
}
@property(assign) float contentHeight;
@property(retain, nonatomic) SBControlCenterContentView* contentView;
@property(retain, nonatomic) _UIBackdropView* backdropView;
-(void)_accessibilityBackgroundContrastDidChange:(id)_accessibilityBackgroundContrast;
-(void)_updateBackground;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

