/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBControlCenterKnockoutView.h"


__attribute__((visibility("hidden")))
@interface SBControlCenterSeparatorView : SBControlCenterKnockoutView {
}
+(float)defaultBreadthForOrientation:(int)orientation;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

