/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"

@class NSString;
@protocol SBControlCenterSectionViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBControlCenterSectionViewController : XXUnknownSuperclass <SBControlCenterObserver> {
	id<SBControlCenterSectionViewControllerDelegate> _delegate;
}
@property(readonly, assign, nonatomic) NSString* sectionIdentifier;
@property(assign, nonatomic) id<SBControlCenterSectionViewControllerDelegate> delegate;
+(Class)viewClass;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)noteSettingsDidUpdate:(id)noteSettings;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(BOOL)enabledForOrientation:(int)orientation;
-(id)view;
-(void)loadView;
@end

