/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBControlCenterSectionViewControllerDelegate <NSObject>
-(void)sectionWantsControlCenterDismissal:(id)dismissal;
-(void)section:(id)section publishStatusUpdate:(id)update;
-(void)noteSectionEnabledStateDidChange:(id)noteSectionEnabledState;
@end

