/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBControlCenterObserver <NSObject>
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
@optional
-(void)controlCenterWillFinishTransitionOpen:(BOOL)controlCenter withDuration:(double)duration;
@end

