/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBControlCenterRootView : XXUnknownSuperclass {
	UIView* _backgroundView;
}
@property(retain, nonatomic) UIView* backgroundView;
-(void)layoutSubviews;
-(void)dealloc;
@end

