/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBCrossfadeZoomSettings.h"


__attribute__((visibility("hidden")))
@interface SBCrossfadeAppLaunchSettings : SBCrossfadeZoomSettings {
}
-(void)setDefaultValues;
@end

