/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImage, NSAttributedString, UILabel;
@protocol SBBulletinDateLabel;

__attribute__((visibility("hidden")))
@interface SBDefaultBannerTextView : XXUnknownSuperclass {
	NSAttributedString* _primaryTextAttributedString;
	NSAttributedString* _primaryTextAttributedStringComponent;
	UIImage* _primaryTextAccessoryImageComponent;
	NSAttributedString* _secondaryTextAttributedString;
	BOOL _secondaryTextItalicized;
	UILabel<SBBulletinDateLabel>* _relevanceDateLabel;
}
@property(readonly, assign, nonatomic) UILabel* relevanceDateLabel;
@property(copy, nonatomic) NSString* secondaryText;
@property(retain, nonatomic) UIImage* primaryTextAccessoryImage;
@property(copy, nonatomic) NSString* primaryText;
+(id)_defaultRelevanceDateFont;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(CGSize)_primaryTextSizeForBounds:(CGRect)bounds;
-(CGSize)_relevanceDateSize;
-(id)_primaryTextAttributedString;
-(void)_invalidatePrimaryTextAttributedString;
-(BOOL)textWillWrapForWidth:(float)text;
-(void)setRelevanceDate:(id)date;
-(void)setSecondaryText:(id)text italicized:(BOOL)italicized;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

