/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUIBannerView.h"
#import "SBVibrantBannerView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBDefaultBannerTextView, UIImageView, SBUIBannerContext, UIView;
@protocol SBDefaultBannerViewSource;

__attribute__((visibility("hidden")))
@interface SBDefaultBannerView : XXUnknownSuperclass <SBUIBannerView, SBVibrantBannerView> {
	SBUIBannerContext* _context;
	id<SBDefaultBannerViewSource> _viewSource;
	UIImageView* _iconImageView;
	SBDefaultBannerTextView* _textView;
	UIImageView* _attachmentImageView;
	CGSize _grabberSize;
	UIView* _grabberView;
}
+(id)defaultColorForElement:(int)element;
+(id)_defaultRelevanceDateColor;
+(id)_defaultGrabberColor;
-(void)setColor:(id)color forElement:(int)element;
-(id)colorForElement:(int)element;
-(void)_setRelevanceDateColor:(id)color;
-(id)_relevanceDateColor;
-(void)_setGrabberColor:(id)color;
-(id)_grabberColor;
-(void)layoutSubviews;
-(id)bannerContext;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithContext:(id)context;
@end

