/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDisableActiveInterfaceOrientationChangeAssertion : XXUnknownSuperclass {
	NSString* _reason;
}
-(id)description;
-(void)dealloc;
-(id)initWithReason:(id)reason;
@end

