/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDistanceFieldView : XXUnknownSuperclass {
}
@property(assign) float lineWidth;
@property(assign) float sharpness;
@property(assign) float offset;
@property(assign) CGColorRef foregroundColor;
@property(assign) BOOL invertsShape;
@property(copy, nonatomic) NSString* renderMode;
+(Class)layerClass;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
@end

