/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStatusBarChangeAssertion.h"


__attribute__((visibility("hidden")))
@interface SBDisableAppStatusBarUserInteractionChangesAssertion : SBStatusBarChangeAssertion {
}
-(void)dealloc;
-(id)initWithReason:(id)reason;
@end

