/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBDisplayProtocol <NSObject>
@property(assign) BOOL expectsFaceContact;
@property(assign) double accelerometerSampleInterval;
@property(assign) BOOL orientationChangedEventsEnabled;
-(id)deactivationValue:(unsigned)value;
-(BOOL)deactivationFlag:(unsigned)flag;
-(void)setDeactivationSetting:(unsigned)setting value:(id)value;
-(void)setDeactivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDeactivationSettings;
-(id)activationValue:(unsigned)value;
-(BOOL)activationFlag:(unsigned)flag;
-(void)setActivationSetting:(unsigned)setting value:(id)value;
-(void)setActivationSetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearActivationSettings;
-(id)displayValue:(unsigned)value;
-(BOOL)displayFlag:(unsigned)flag;
-(void)setDisplaySetting:(unsigned)setting value:(id)value;
-(void)setDisplaySetting:(unsigned)setting flag:(BOOL)flag;
-(void)clearDisplaySettings;
-(BOOL)expectsFaceContactInLandscape;
-(void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
-(void)deactivate;
-(void)activate;
-(double)autoLockTime;
-(double)autoDimTime;
-(BOOL)suppressesControlCenter;
-(BOOL)suppressesNotificationCenter;
-(BOOL)suppressesBanners;
-(BOOL)allowsEventOnlySuspension;
-(id)effectiveStatusBarStyleRequest;
-(id)statusBarStyleRequest;
-(int)starkStatusBarStyle;
-(int)statusBarStyle;
@end

