/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLeafIcon.h"

@class SBApplicationPlaceholder;

__attribute__((visibility("hidden")))
@interface SBDownloadingIcon : SBLeafIcon {
	BOOL _wasUninstalledByUser;
	BOOL _isNewsstandDownload;
	SBApplicationPlaceholder* _appPlaceholder;
}
@property(assign) BOOL uninstalledByUser;
@property(assign, getter=isNewsstandDownload) BOOL newsstandDownload;
@property(readonly, retain) SBApplicationPlaceholder* appPlaceholder;
+(id)leafIdentifierForApplicationPlaceholderBundleID:(id)applicationPlaceholderBundleID;
-(BOOL)isDownloadingIcon;
-(void)cancelDownload;
-(BOOL)iconAppearsInNewsstand;
-(void)_showAlertForError:(id)error;
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitle;
-(void)setApplicationPlaceholder:(id)placeholder;
-(void)reloadForStatusChange;
-(void)completeUninstall;
-(id)realDisplayName;
-(id)homescreenIconImage;
-(id)_darkenedIconImageForImage:(id)image;
-(id)gridCellImage;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithApplicationPlaceholder:(id)applicationPlaceholder;
@end

