/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBFakeStatusBarView : XXUnknownSuperclass {
	NSString* _cacheKey;
}
@property(copy, nonatomic) NSString* cacheKey;
-(void)setSnapshotOverridesWithTimeEnabled:(BOOL)timeEnabled;
-(void)dealloc;
@end

