/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"
#import "SBFolderView.h"

@class SBFolderBackgroundView, UIView, UITapGestureRecognizer, UIPinchGestureRecognizer, SBFolderSettings, UILongPressGestureRecognizer;

__attribute__((visibility("hidden")))
@interface SBFloatyFolderView : SBFolderView <UIGestureRecognizerDelegate, _UISettingsKeyObserver> {
	UIView* _scrollClipView;
	SBFolderBackgroundView* _backgroundView;
	UITapGestureRecognizer* _tapGesture;
	UIPinchGestureRecognizer* _pinchGesture;
	UILongPressGestureRecognizer* _longPressGesture;
	SBFolderSettings* _folderSettings;
}
-(void)settings:(id)settings changedValueForKey:(id)key;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)_tapToCloseGestureRecognizer:(id)closeGestureRecognizer shouldReceiveTouch:(id)touch;
-(void)_handleLongPressGesture:(id)gesture;
-(void)_handlePinchGesture:(id)gesture;
-(void)_handleOutsideTap:(id)tap;
-(void)_configureGestures;
-(void)fadeContentForMinificationFraction:(float)minificationFraction;
-(void)fadeContentForMagnificationFraction:(float)magnificationFraction;
-(void)didAnimate;
-(void)willAnimate;
-(float)_titleFontSize;
-(BOOL)_showsTitle;
-(BOOL)locationCountsAsInsideFolder:(CGPoint)folder;
-(CGRect)_frameForScalingView;
-(void)_layoutSubviews;
-(void)setLegibilitySettings:(id)settings;
-(CGPoint)visibleFolderRelativeImageCenterForIcon:(id)icon;
-(void)setBackgroundAlpha:(float)alpha;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
@end

