/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBFLockScreenDateFormatter <NSObject>
-(void)resetFormattersIfNecessary;
-(id)formatDateAsDayOfWeekMonthDayStyle:(id)weekMonthDayStyle;
-(id)formatDateAsTimeNoAMPM:(id)ampm;
@end

