/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconBlurryBackgroundView.h"


__attribute__((visibility("hidden")))
@interface SBFolderIconBackgroundView : SBIconBlurryBackgroundView {
}
-(void)setWallpaperColor:(CGColorRef)color phase:(CGSize)phase;
-(id)_contentsImageForColor:(CGColorRef)color;
-(id)initWithDefaultSize;
@end

