/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFolderZoomSettings.h"


__attribute__((visibility("hidden")))
@interface SBFolderOpenSettings : SBFolderZoomSettings {
}
-(void)setDefaultValues;
@end

