/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconFadeAnimator.h"

@class SBFolderController;

__attribute__((visibility("hidden")))
@interface SBFolderIconFadeAnimator : SBIconFadeAnimator {
	SBFolderController* _innerFolderController;
}
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController innerController:(id)controller;
@end

