/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWallpaperObserver.h"
#import "_UISettingsKeyObserver.h"

@class UIImageView, _UILegibilitySettings, SBFolderSettings, SBWallpaperEffectView;

__attribute__((visibility("hidden")))
@interface SBFolderBackgroundView : XXUnknownSuperclass <_UISettingsKeyObserver, SBWallpaperObserver> {
	SBWallpaperEffectView* _backdropView;
	UIImageView* _backgroundImageView;
	SBFolderSettings* _folderSettings;
	_UILegibilitySettings* _legibilitySettings;
}
@property(retain, nonatomic) _UILegibilitySettings* legibilitySettings;
+(float)cornerRadiusToInsetContent;
+(CGSize)folderBackgroundSize;
+(void)warmupIfNecessary;
-(void)wallpaperDidChangeForVariant:(int)wallpaper;
-(void)_backgroundContrastDidChange:(id)_backgroundContrast;
-(void)_updateBackgroundImageView;
-(BOOL)_shouldUseDarkBackground;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_configureBackground;
-(void)adjustCornerRadiusForMagnificationFraction:(float)magnificationFraction;
-(void)didAnimate;
-(void)willAnimate;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

