/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBFolderSettings : XXUnknownSuperclass {
	BOOL _allowNestedFolders;
	BOOL _pinchToClose;
	BOOL _blurFolderBackground;
	BOOL _oneColumnAtATime;
}
@property(assign, nonatomic) BOOL oneColumnAtATime;
@property(assign, nonatomic) BOOL blurFolderBackground;
@property(assign, nonatomic) BOOL pinchToClose;
@property(assign, nonatomic) BOOL allowNestedFolders;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

