/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIconObserver.h"
#import "SBIconBlurryBackgroundViewObserver.h"
#import "SBIconImageView.h"

@class SBFloatyFolderView, _SBIconGridWrapperView, UIView, SBFolderIconBackgroundView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBFolderIconImageView : SBIconImageView <SBFolderIconObserver, SBIconBlurryBackgroundViewObserver> {
	SBFolderIconBackgroundView* _backgroundView;
	UIView* _pageGridContainer;
	_SBIconGridWrapperView* _leftWrapperView;
	_SBIconGridWrapperView* _rightWrapperView;
	NSMutableArray* _pageElements;
	unsigned _currentPageIndex;
	SBFloatyFolderView* _crossfadeFolderView;
	UIView* _crossfadeScalingView;
	BOOL _animating;
}
@property(readonly, retain) SBFolderIconBackgroundView* backgroundView;
-(void)_showRightMinigrid;
-(void)_showLeftMinigrid;
-(void)_setPageElements:(id)elements;
-(void)_setupGridViewsInDefaultConfiguration;
-(id)_currentPageElement;
-(id)_folderIcon;
-(CGSize)_interiorGridSizeClipRect;
-(CGSize)_interPageSpacing;
-(Class)_iconGridImageClass;
-(void)_performScrollingMovingToLeft:(BOOL)left movingToRight:(BOOL)right targetPageIndex:(unsigned)index targetPageScrollRow:(unsigned)row newLeftElement:(id)element newRightElement:(id)element6 animated:(BOOL)animated;
-(void)_updateRasterization;
-(void)_setAnimating:(BOOL)animating;
-(void)blurryBackgroundViewDidChangeWhetherBlurring:(id)blurryBackgroundView;
-(void)folderIcon:(id)icon didUpdateGridImage:(id)image forListIndex:(unsigned)listIndex forContainedIconImageUpdate:(id)containedIconImageUpdate;
-(void)cleanupAfterFloatyFolderCrossfade;
-(void)setFloatyFolderCrossfadeFraction:(float)fraction;
-(void)prepareToCrossfadeWithFloatyFolderView:(id)floatyFolderView allowFolderInteraction:(BOOL)interaction;
-(void)setSuppressesBlurryBackgroundChanges:(BOOL)changes;
-(void)setWallpaperRelativeCenter:(CGPoint)center;
-(void)setBackgroundScale:(float)scale;
-(void)setBackgroundAndIconGridImageAlpha:(float)alpha;
-(void)setIconGridImageAlpha:(float)alpha;
-(CGRect)frameForMiniIconAtIndexPath:(id)indexPath;
-(CGRect)visibleImageRelativeFrameForMiniIconAtIndex:(unsigned)index;
-(CGRect)frameForMiniIconAtIndex:(unsigned)index;
-(unsigned)lastVisibleMiniIconIndex;
-(unsigned)centerVisibleMiniIconIndex;
-(unsigned)firstVisibleMiniIconIndex;
-(unsigned)visibleMiniIconListIndex;
-(unsigned)visibleMiniIconCount;
-(void)scrollToGapOrTopIfFullOfPage:(unsigned)page animated:(BOOL)animated;
-(void)scrollToTopOfPage:(unsigned)page animated:(BOOL)animated;
-(void)scrollToFirstGapAnimated:(BOOL)firstGapAnimated;
-(void)scrollToTopOfFirstPageAnimated:(BOOL)firstPageAnimated;
-(void)layoutSubviews;
-(id)snapshot;
-(void)prepareForReuse;
-(void)updateImageAnimated:(BOOL)animated;
-(id)darkeningOverlayImage;
-(id)_generateSquareContentsImage;
-(id)contentsImage;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

