/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


__attribute__((visibility("hidden")))
@interface SBFolderIconListView : SBIconListView {
}
+(unsigned)maxVisibleIconRowsInterfaceOrientation:(int)orientation;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
-(int)iconLocation;
-(float)sideIconInset;
-(float)bottomIconInset;
-(float)topIconInset;
@end

