/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBFolderViewDelegate <NSObject>
-(void)folderViewShouldBeginEditing:(id)folderView;
-(void)folderViewShouldClose:(id)folderView;
-(void)folderViewDidEndScrolling:(id)folderView;
-(void)folderViewWillBeginScrolling:(id)folderView;
-(void)folderView:(id)view currentPageIndexDidChange:(int)currentPageIndex;
-(Class)iconListViewClassForFolderView:(id)folderView;
@end

