/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, SBWindow, UIScreen;

__attribute__((visibility("hidden")))
@interface SBFolderControllerAnimationContext : XXUnknownSuperclass {
	UIScreen* _screen;
	SBWindow* _animationWindow;
	UIView* _fallbackIconContainer;
}
@property(readonly, assign, nonatomic) UIView* fallbackIconContainer;
@property(readonly, assign, nonatomic) SBWindow* animationWindow;
@property(readonly, assign, nonatomic) UIScreen* screen;
+(id)contextWithScreen:(id)screen animationWindow:(id)window fallbackIconContainer:(id)container;
-(void)dealloc;
-(id)initWithScreen:(id)screen animationWindow:(id)window fallbackIconContainer:(id)container;
@end

