/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBZoomView.h"


__attribute__((visibility("hidden")))
@interface SBFullscreenZoomView : SBZoomView {
	BOOL _hasImage;
	BOOL _hasFullSizedImage;
	id _surface;
}
@property(readonly, retain) id surface;
-(void)dealloc;
-(void)_addBlackBackground;
-(id)initWithContextHostView:(id)contextHostView screen:(id)screen;
-(id)initWithImage:(id)image screen:(id)screen opaque:(BOOL)opaque;
-(id)initWithSnapshotFrame:(CGRect)snapshotFrame screen:(id)screen ioSurface:(void*)surface opaque:(BOOL)opaque snapshotTransform:(CGAffineTransform)transform;
-(id)initWithSnapshotFrame:(CGRect)snapshotFrame screen:(id)screen image:(id)image originalImageOrientation:(int)orientation currentImageOrientation:(int)orientation5 interfaceOrientation:(int)orientation6 doubleHeightStatusBar:(BOOL)bar preventSplit:(BOOL)split needsZoomFilter:(BOOL)filter asyncDecodeImage:(BOOL)image10 opaque:(BOOL)opaque forJail:(BOOL)jail;
-(id)_initWithView:(id)view screen:(id)screen needsBlackBackground:(BOOL)background;
-(id)_initWithFrame:(CGRect)frame;
@end

