/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBFWallpaperViewLegibilityObserver <NSObject>
-(void)wallpaperView:(id)view legibilitySettingsDidChange:(id)legibilitySettings;
@end

