/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBFWallpaperViewInternalObserver <NSObject>
-(void)wallpaperViewDidChangeWantsRasterization:(id)wallpaperView;
-(void)wallpaperView:(id)view didChangeZoomFactor:(float)factor;
-(void)wallpaperViewDidInvalidateGeometry:(id)wallpaperView;
-(void)wallpaperViewDidInvalidateBlurs:(id)wallpaperView;
@end

