/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface SBGradientView : XXUnknownSuperclass {
	NSArray* _colors;
}
@property(assign) CGPoint endPoint;
@property(assign) CGPoint startPoint;
@property(copy, nonatomic) NSArray* locations;
@property(copy, nonatomic) NSArray* colors;
+(Class)layerClass;
-(id)color;
@end

