/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBFolderView, SBIconViewMap;

__attribute__((visibility("hidden")))
@interface SBHomeScreenPreviewView : XXUnknownSuperclass <SBFolderViewDelegate> {
	SBIconViewMap* _viewMap;
	SBFolderView* _folderContent;
}
+(void)cleanupPreview;
+(id)preview;
-(void)folderViewShouldBeginEditing:(id)folderView;
-(void)folderViewShouldClose:(id)folderView;
-(void)folderViewDidEndScrolling:(id)folderView;
-(void)folderViewWillBeginScrolling:(id)folderView;
-(void)folderView:(id)view currentPageIndexDidChange:(int)currentPageIndex;
-(Class)iconListViewClassForFolderView:(id)folderView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame iconController:(id)controller;
@end

