/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSCopying.h"
#import "NSMutableCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIColor, UIFont;

__attribute__((visibility("hidden")))
@interface SBIconLabelImageParameters : XXUnknownSuperclass <NSCopying, NSMutableCopying> {
	UIFont* _font;
	NSString* _text;
	BOOL _containsNonLatinLikeCharacters;
	BOOL _containsEmoji;
	BOOL _canEllipsize;
	float _scale;
	CGSize _maxSize;
	int _style;
	UIColor* _textColor;
	BOOL _recalculateHash;
	BOOL _canUseMemoryPool;
	BOOL _accessibilityIncreaseContrastEnabled;
	UIColor* _focusHighlightColor;
	UIEdgeInsets _textInsets;
	unsigned _hash;
}
@property(readonly, assign, nonatomic) UIEdgeInsets textInsets;
@property(readonly, assign, nonatomic) UIColor* focusHighlightColor;
@property(readonly, assign, nonatomic) BOOL accessibilityIncreaseContrastEnabled;
@property(readonly, assign, nonatomic) UIColor* textColor;
@property(readonly, assign, nonatomic) int style;
@property(readonly, assign, nonatomic) BOOL canUseMemoryPool;
@property(readonly, assign, nonatomic) BOOL containsEmoji;
@property(readonly, assign, nonatomic) BOOL containsNonLatinLikeCharacters;
@property(readonly, assign, nonatomic) BOOL canEllipsize;
@property(readonly, assign, nonatomic) float scale;
@property(readonly, assign, nonatomic) UIFont* font;
@property(readonly, assign, nonatomic) CGSize maxSize;
@property(readonly, assign, nonatomic) NSString* text;
@property(readonly, assign) unsigned hash;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)copyWithZone:(NSZone*)zone;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(void)_noteNeedsHashRecalculation;
-(BOOL)colorspaceIsGrayscale;
-(void)dealloc;
-(id)initWithParameters:(id)parameters;
-(id)init;
@end

