/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconListLayoutDelegate <NSObject>
@optional
-(void)iconListViewLayoutInvalidated:(id)invalidated;
-(void)iconListView:(id)view wouldHaveMovedIcon:(id)icon;
@end

