/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconAnimator.h"
#import "SBIconIndexNodeObserver.h"

@class NSMapTable, SBIconListView, SBIconZoomSettings, SBIconListModel, NSSet;

__attribute__((visibility("hidden")))
@interface SBIconZoomAnimator : SBIconAnimator <SBIconIndexNodeObserver> {
	NSMapTable* _listIconToViewMap;
	NSMapTable* _dockIconToViewMap;
	NSSet* _criticalIconNodeIdentifiers;
	SBIconListModel* _iconListModel;
	SBIconListView* _iconListView;
	SBIconListView* _dockListView;
}
@property(retain, nonatomic) NSSet* criticalIconNodeIdentifiers;
@property(readonly, assign, nonatomic) SBIconListView* dockListView;
@property(readonly, assign, nonatomic) SBIconListView* iconListView;
@property(retain, nonatomic) SBIconZoomSettings* settings;
-(void)_invalidateAnimationForSignificantIconModelChangesForReason:(id)reason;
-(void)_iconModelDidReload;
-(void)_iconModelDidRelayout;
-(void)_clearObservers;
-(void)_setDockListView:(id)view;
-(void)_setIconListView:(id)view;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(void)_applyLabelAlphaFraction:(float)fraction;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(unsigned)dockIconCount;
-(unsigned)listIconCount;
-(void)enumerateIconsAndIconViewsWithHandler:(id)handler;
-(id)iconViewForIcon:(id)icon;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController;
@end

