/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconAnimatorDelegate <NSObject>
-(void)iconAnimatorWasInvalidated:(id)invalidated;
@end

