/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconStateUnarchiveContext.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSMutableSet, SBIconModel;
@protocol SBIconIndexNode;

__attribute__((visibility("hidden")))
@interface SBIconStateUnarchiveResult : XXUnknownSuperclass <SBIconStateUnarchiveContext> {
	SBIconModel* _iconSource;
	id<SBIconIndexNode> _node;
	NSMutableArray* _folderStack;
	int _parseDepth;
	NSMutableSet* _nodeIdentifiersUnarchived;
	BOOL _corrupted;
	BOOL _dirty;
}
@property(retain, nonatomic, setter=_setIconSource:) SBIconModel* _iconSource;
@property(readonly, assign, nonatomic, getter=isDirty) BOOL dirty;
@property(readonly, assign, nonatomic, getter=isValid) BOOL valid;
@property(retain, nonatomic) id<SBIconIndexNode> node;
-(void)_setNode:(id)node;
-(void)_noteNodeIdentifierWasUnarchived:(id)unarchived;
-(BOOL)_isNodeIdentifierAlreadyUnarchived:(id)unarchived;
-(void)_noteSignificantDeviation;
-(void)_noteRepresentationIsCorrupted;
-(int)_currentParseDepth;
-(void)_noteExitedNode;
-(void)_noteEnteredNode;
-(id)_popFolder;
-(id)_currentFolder;
-(void)_pushFolder:(id)folder;
-(void)dealloc;
@end

