/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconAnimationSettings.h"


__attribute__((visibility("hidden")))
@interface SBIconZoomSettings : SBIconAnimationSettings {
	BOOL _labelAlphaWithZoom;
}
@property(assign) BOOL labelAlphaWithZoom;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

