/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBIconContentView : XXUnknownSuperclass {
	int _orientation;
	NSMutableArray* _folderContentViews;
}
@property(assign, nonatomic) int orientation;
-(void)layoutSubviews;
-(void)didAddSubview:(id)subview;
-(CGRect)_frameForFolderView:(id)folderView;
-(id)_folderViews;
-(void)clearAllFolderContentViews;
-(void)popFolderContentView:(id)view;
-(void)pushFolderContentView:(id)view;
-(void)updateLayoutWithDuration:(double)duration;
-(void)dealloc;
-(id)initWithOrientation:(int)orientation;
@end

