/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBReusableViewMapDelegate.h"


@protocol SBIconViewMapDelegate <SBReusableViewMapDelegate>
-(int)viewMap:(id)map locationForIcon:(id)icon;
-(Class)iconViewClassForIcon:(id)icon location:(int)location;
@optional
-(unsigned)viewMap:(id)map numberOfViewsToPrepareOfClass:(Class)aClass;
-(id)viewMapShouldPrepareViewsOfClasses:(id)viewMap;
@end

