/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBRootFolder, NSMutableDictionary, NSDictionary, NSSet, NSOrderedSet;
@protocol SBIconModelApplicationDataSource, SBIconModelStore, SBIconModelDelegate;

__attribute__((visibility("hidden")))
@interface SBIconModel : XXUnknownSuperclass {
	NSDictionary* _desiredIconState;
	NSOrderedSet* _desiredIconStateFlattened;
	NSMutableDictionary* _leafIconsByIdentifier;
	NSSet* _hiddenIconTags;
	NSSet* _visibleIconTags;
	BOOL _tagsHaveBeenSet;
	SBRootFolder* _rootFolder;
	id<SBIconModelStore> _store;
	id<SBIconModelApplicationDataSource> _applicationDataSource;
	id<SBIconModelDelegate> _delegate;
	BOOL _allowsSaving;
}
@property(retain, nonatomic) NSDictionary* leafIconsByIdentifier;
@property(readonly, assign, nonatomic) id<SBIconModelApplicationDataSource> applicationDataSource;
@property(readonly, assign, nonatomic) id<SBIconModelStore> store;
@property(assign, nonatomic) id<SBIconModelDelegate> delegate;
@property(assign, nonatomic) BOOL allowsSaving;
@property(readonly, retain) SBRootFolder* rootFolder;
-(BOOL)importState:(id)state;
-(id)exportFlattenedState:(BOOL)state includeMissingIcons:(BOOL)icons;
-(id)exportPendingState:(BOOL)state includeMissingIcons:(BOOL)icons;
-(id)exportState:(BOOL)state;
-(id)forecastedLayoutForIconState:(id)iconState includeMissingIcons:(BOOL)icons;
-(void)layout;
-(void)_replaceAppIconsWithDownloadingIcons:(id)downloadingIcons;
-(void)_replaceAppIconsWithDownloadingIcons;
-(void)saveIconState;
-(void)_saveDesiredIconState;
-(void)deleteIconState;
-(id)_indexPathInRootFolder:(id)rootFolder forNewIcon:(id)newIcon isDesignatedLocation:(BOOL*)location replaceExistingIconAtIndexPath:(id*)indexPath;
-(id)indexPathForNewIcon:(id)newIcon isDesignatedLocation:(BOOL*)location replaceExistingIconAtIndexPath:(id*)indexPath;
-(void)clearDesiredIconStateIfPossible;
-(void)clearDesiredIconState;
-(BOOL)hasDesiredIconState;
-(id)indexPathForIconInPlatformState:(id)platformState;
-(void)removeIconForIdentifier:(id)identifier;
-(void)removeIcon:(id)icon;
-(void)addIcon:(id)icon;
-(id)_unarchiveRootFolder;
-(id)_iconState;
-(id)iconState;
-(id)applicationIconForDisplayIdentifier:(id)displayIdentifier;
-(id)leafIconForIdentifier:(id)identifier;
-(id)expectedIconForDisplayIdentifier:(id)displayIdentifier;
-(id)_applicationIcons;
-(id)leafIcons;
-(id)visibleIconIdentifiers;
-(void)loadAllIcons;
-(void)addIconForApplication:(id)application;
-(id)addBookmarkIconForWebClip:(id)webClip;
-(id)leafIconForWebClipIdentifier:(id)webClipIdentifier;
-(id)leafIconForWebClip:(id)webClip;
-(id)downloadingIconForBundleIdentifier:(id)bundleIdentifier;
-(id)addDownloadingIconForBundleID:(id)bundleID withIdentifier:(id)identifier;
-(id)addDownloadingIconForDownload:(id)download;
-(BOOL)_canAddDownloadingIconForBundleID:(id)bundleID;
-(BOOL)isIconVisible:(id)visible;
-(void)setVisibilityOfIconsWithVisibleTags:(id)visibleTags hiddenTags:(id)tags;
-(void)_postIconVisibilityChangedNotificationShowing:(id)showing hiding:(id)hiding;
-(void)localeChanged;
-(id)newsstandIcon;
-(id)_newsstandIconInFolder:(id)folder outIndexPath:(id*)path;
-(void)dealloc;
-(id)initWithStore:(id)store applicationDataSource:(id)source;
@end

