/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBCountedMapValue.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBIconAccessoryImage : XXUnknownSuperclass <SBCountedMapValue> {
	NSString* _countedMapKey;
}
@property(copy, nonatomic) NSString* countedMapKey;
-(void)dealloc;
-(id)initWithImage:(id)image;
@end

