/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBIconView, SBIcon, SBIconViewMap;

__attribute__((visibility("hidden")))
@interface SBIconRotationContainer : XXUnknownSuperclass {
	SBIconCoordinate _coordinate;
	SBIconViewMap* _viewMap;
	SBIconView* _startView;
	SBIconView* _endView;
	CGPoint _wallpaperRelativeImageCenter;
}
@property(readonly, assign, nonatomic) CGPoint iconImageCenter;
@property(assign, nonatomic) CGPoint wallpaperRelativeImageCenter;
@property(readonly, assign, nonatomic) SBIconCoordinate coordinate;
@property(readonly, assign, nonatomic) SBIcon* endIcon;
-(void)crossfadeWithDuration:(double)duration;
-(void)prepareToCrossfade;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame startIcon:(id)icon endIcon:(id)icon3 viewMap:(id)map coordinate:(SBIconCoordinate)coordinate;
@end

