/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFolderControllerAnimationContext, NSMutableArray, NSString, SBFolderController, SBIconAnimationSettings, UIView;
@protocol SBIconAnimatorDelegate;

__attribute__((visibility("hidden")))
@interface SBIconAnimator : XXUnknownSuperclass {
	float _fraction;
	BOOL _startedAnimation;
	BOOL _startAnimationAfterRotationEnds;
	BOOL _windowIsRotating;
	BOOL _cleanedUp;
	NSMutableArray* _pendedAnimationContexts;
	SBFolderControllerAnimationContext* _animationContext;
	NSString* _instanceIdentifier;
	BOOL _invalidated;
	id<SBIconAnimatorDelegate> _delegate;
	SBIconAnimationSettings* _settings;
	SBFolderController* _folderController;
}
@property(readonly, assign, nonatomic) UIView* referenceView;
@property(readonly, assign, nonatomic) SBFolderControllerAnimationContext* animationContext;
@property(readonly, assign, nonatomic) SBFolderController* folderController;
@property(assign, nonatomic) BOOL invalidated;
@property(retain, nonatomic) SBIconAnimationSettings* settings;
@property(assign, nonatomic) id<SBIconAnimatorDelegate> delegate;
-(void)_windowFinishedRotating;
-(void)_invalidateCompletions;
-(void)_allowRotationOnMainWindowIfNecessary:(BOOL)necessary;
-(id)_centralAnimationFactory;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(BOOL)_isDelayedForRotation;
-(void)_animateToFractionFromContext:(id)context;
-(void)_animateToFractionFromPendingContexts;
-(void)cleanup;
-(void)animateToFraction:(float)fraction afterDelay:(double)delay withCompletion:(id)completion;
-(void)setFraction:(float)fraction;
-(void)prepare;
-(id)centralAnimationFactory;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController;
@end

