/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBIconBlurryBackgroundViewObserver <NSObject>
-(void)blurryBackgroundViewDidChangeWhetherBlurring:(id)blurryBackgroundView;
@end

