/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "_UISettingsKeyObserver.h"
#import "SBIconBadgeView.h"

@class SBFParallaxSettings;

__attribute__((visibility("hidden")))
@interface SBIconParallaxBadgeView : SBIconBadgeView <_UISettingsKeyObserver> {
	SBFParallaxSettings* _parallaxSettings;
}
-(void)_applyParallaxSettings;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)dealloc;
-(id)init;
@end

