/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconObserver.h"
#import "SBReusableViewMap.h"
#import "SBIconIndexNodeObserver.h"
#import "SBIconViewObserver.h"

@class NSMapTable, _UILegibilitySettings, SBIconModel;
@protocol SBIconViewMapDelegate, SBIconViewDelegate;

__attribute__((visibility("hidden")))
@interface SBIconViewMap : SBReusableViewMap <SBIconObserver, SBIconIndexNodeObserver, SBIconViewObserver> {
	SBIconModel* _model;
	NSMapTable* _iconViewsForIcons;
	id<SBIconViewMapDelegate> _delegate;
	id<SBIconViewDelegate> _viewDelegate;
	NSMapTable* _labelsForIcons;
	NSMapTable* _lightLegibilityImagesForIcons;
	NSMapTable* _darkLegibilityImagesForIcons;
	NSMapTable* _accessoryImagesForIcons;
	_UILegibilitySettings* _legibilitySettings;
}
@property(retain, nonatomic) _UILegibilitySettings* legibilitySettings;
@property(readonly, assign, nonatomic) SBIconModel* iconModel;
+(id)homescreenMap;
-(void)iconViewDidChangeLocation:(id)iconView;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)_modelReloadedState;
-(void)_modelWillReloadState;
-(void)_modelReloadedIcons;
-(void)_modelRemovedIcon:(id)icon;
-(void)_observeIconAndCacheIfNecessary:(id)necessary;
-(void)_cacheAccessoryImagesForIcon:(id)icon location:(int*)location;
-(void)_cacheLabelImagesForIcon:(id)icon location:(int*)location;
-(void)_cacheImagesForIcon:(id)icon;
-(void)purgeRecycledIconViewsForClass:(Class)aClass;
-(void)recycleAndPurgeAll;
-(void)recycleIconView:(id)view;
-(id)extraIconViewForIcon:(id)icon;
-(void)recycleViewForIcon:(id)icon;
-(void)_recycleIconView:(id)view;
-(void)purgeIconFromMap:(id)map;
-(void)_addIconView:(id)view forIcon:(id)icon;
-(void)tryToReplaceIcon:(id)replaceIcon withIcon:(id)icon;
-(id)iconViewForIcon:(id)icon;
-(id)_iconViewForIcon:(id)icon;
-(id)newViewOfClass:(Class)aClass;
-(id)mappedIconViewForIcon:(id)icon;
-(void)invalidate;
-(void)dealloc;
-(id)initWithIconModel:(id)iconModel delegate:(id)delegate viewDelegate:(id)delegate3;
@end

