/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBIconAnimationContext : XXUnknownSuperclass {
	float _fraction;
	id _completion;
	double _delay;
}
@property(copy, nonatomic) id completion;
@property(assign, nonatomic) float fraction;
@property(assign, nonatomic) double delay;
-(void)invalidate;
-(void)dealloc;
-(id)initWithNotificationIdentifier:(id)notificationIdentifier;
@end

