/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFAnimationSettings;

__attribute__((visibility("hidden")))
@interface SBIconAnimationSettings : XXUnknownSuperclass {
	SBFAnimationSettings* _centralAnimationSettings;
}
@property(retain) SBFAnimationSettings* centralAnimationSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

