/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBImageAlertView : XXUnknownSuperclass {
	BOOL _showingImage;
}
@property(readonly, assign, getter=isShowingImage) BOOL showingImage;
-(void)setImage:(id)image;
-(void)layout;
@end

