/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenLegalViewController : XXUnknownSuperclass {
}
-(BOOL)_shouldShowLegalText;
-(id)_legalString;
-(id)legalView;
-(void)loadView;
@end

