/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenBatteryFillView : XXUnknownSuperclass {
	int _chargePercentage;
}
-(void)drawRect:(CGRect)rect;
-(void)setChargePercentage:(int)percentage;
@end

