/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayView.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenInfoOverlayView : SBLockOverlayView {
}
-(id)_actionFont;
-(id)_subtitleFont;
@end

