/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationBannerItemFactory : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(id)bannerItemWithAwayListItem:(id)awayListItem unlockActionHandler:(id)handler delegate:(id)delegate;
-(BOOL)supportsAwayListItem:(id)item;
@end

