/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockScreenNotificationModel <NSObject>
-(id)listItemAtIndexPath:(id)indexPath;
-(unsigned)count;
@end

