/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBInteractionPassThroughView.h"

@class UIButton, SBLockOverlayStylePropertiesFactory, _UILegibilitySettings, UIResizableView, UILabel;
@protocol SBLockOverlayViewDelegate;

__attribute__((visibility("hidden")))
@interface SBLockOverlayView : SBInteractionPassThroughView {
	id<SBLockOverlayViewDelegate> _delegate;
	UIResizableView* _textContainerView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIButton* _actionButton;
	BOOL _hidesLockContent;
	SBLockOverlayStylePropertiesFactory* _underlayPropertiesFactory;
	unsigned _style;
	_UILegibilitySettings* _legibilitySettings;
}
@property(readonly, assign, nonatomic) UIButton* actionButton;
@property(readonly, assign, nonatomic) UILabel* subtitleLabel;
@property(readonly, assign, nonatomic) UILabel* titleLabel;
@property(readonly, assign, nonatomic) _UILegibilitySettings* legibilitySettings;
@property(readonly, assign, nonatomic) SBLockOverlayStylePropertiesFactory* underlayPropertiesFactory;
@property(readonly, assign, nonatomic) unsigned style;
@property(readonly, assign, nonatomic) BOOL hidesLockContent;
@property(assign, nonatomic) id<SBLockOverlayViewDelegate> delegate;
-(float)_maxLabelWidth;
-(void)_sizeView:(id)view forFixedWith:(BOOL)with;
-(unsigned)_numberOfLinesForText:(id)text font:(id)font size:(CGSize)size;
-(void)_buttonPressed;
-(id)_actionFont;
-(id)_subtitleFont;
-(id)_titleFont;
-(void)layoutSubviews;
-(id)_legibilitySettingsForStyle:(unsigned)style;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame style:(unsigned)style;
-(id)initWithFrame:(CGRect)frame;
@end

