/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"

@class NSString, SBLockScreenTemperatureWarningView;

__attribute__((visibility("hidden")))
@interface SBLockScreenTemperatureWarningViewController : SBLockOverlayViewController {
	SBLockScreenTemperatureWarningView* _warningView;
}
@property(readonly, assign, nonatomic) NSString* slideToUnlockText;
-(void)loadView;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

