/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewDelegate.h"


@protocol SBLockScreenBuddyViewDelegate <SBLockOverlayViewDelegate>
-(void)buddyView:(id)view didChangeToStyle:(unsigned)style;
@end

