/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewController.h"
#import "SBLockOverlayViewDelegate.h"

@class SBLockScreenInfoOverlayView, NSString;
@protocol SBLockScreenInfoOverlayDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenInfoOverlayViewController : SBLockOverlayViewController <SBLockOverlayViewDelegate> {
	SBLockScreenInfoOverlayView* _overlayView;
	NSString* _title;
}
@property(assign, nonatomic) id<SBLockScreenInfoOverlayDelegate> delegate;
-(void)handleTapGestureFromView:(id)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithTitle:(id)title;
@end

