/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockScreenPluginTransition.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenAnimatedPluginTransition : SBLockScreenPluginTransition {
}
-(void)_finalizeAndClearPluginAnimationContext;
-(void)beginTransition;
@end

