/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBLockScreenBatteryChargingView, NSTimer;
@protocol SBLockScreenBatteryChargingViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenBatteryChargingViewController : XXUnknownSuperclass {
	SBLockScreenBatteryChargingView* _chargingView;
	NSTimer* _visibilityTimer;
	BOOL _displayDetailedCharge;
	int _chargePercentage;
	id<SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBLockScreenBatteryChargingViewControllerDelegate> delegate;
@property(readonly, retain) SBLockScreenBatteryChargingView* chargingView;
-(void)_batteryStatusChanged:(id)changed;
-(void)_visibilityTimerFired:(id)fired;
-(void)showChargeLevelWithBatteryVisible:(BOOL)batteryVisible;
-(BOOL)batteryVisible;
-(void)_clearVisibilityTimer;
-(void)prepareForDismissal;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

