/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBFLockScreenSimpleDateFormatter, SBFLockScreenDateView, UIView, _UILegibilitySettings, _UILegibilityLabel, SBFakeStatusBarView, UILabel, SBLegibilityView;

__attribute__((visibility("hidden")))
@interface SBLockScreenPreviewView : XXUnknownSuperclass {
	UIView* _wallpaperView;
	SBFLockScreenDateView* _dateView;
	SBLegibilityView* _cameraView;
	UILabel* _slideToUnlockView;
	_UILegibilityLabel* _slideToUnlockLegibilityLabel;
	SBFakeStatusBarView* _statusBar;
	SBFLockScreenSimpleDateFormatter* _dateFormatter;
	_UILegibilitySettings* _legibilitySettings;
}
+(id)preview;
-(void)_layoutWallpaperView;
-(void)_layoutSlideToUnlockView;
-(void)_layoutDateView;
-(void)_layoutCameraView;
-(void)_layoutStatusBar;
-(void)layoutSubviews;
-(id)_legibilityPrototypeSettings;
-(void)_setupStatusBar;
-(void)_setupCameraView;
-(void)_setupDateView;
-(void)_setupSlideToUnlockView;
-(void)_setupWallpaperView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame legibilitySettings:(id)settings;
@end

