/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLockScreenNotificationCell.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenBulletinCell : SBLockScreenNotificationCell {
}
+(float)paddingBetweenTitleAndRelevanceDate;
+(float)rowHeightForTitle:(id)title subtitle:(id)subtitle body:(id)body maxLines:(unsigned)lines attachmentSize:(CGSize)size datesVisible:(BOOL)visible rowWidth:(float)width includeUnlockActionText:(BOOL)text;
@end

