/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnlockActionHandler.h"


@protocol SBLockScreenNotificationViewDelegate <SBUnlockActionHandler>
-(void)listView:(id)view cellDidEndScrolling:(id)cell;
-(void)listView:(id)view cellDidBeginScrolling:(id)cell;
-(void)listViewDidEndScrolling:(id)listView;
-(void)listViewDidBeginScrolling:(id)listView;
-(id)lockScreenScrollView;
-(void)noteUnlockActionChanged:(id)changed;
@end

