/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIAlertView, UIView;

__attribute__((visibility("hidden")))
@interface SBLockScreenModalAlertView : XXUnknownSuperclass {
	UIAlertView* _alertView;
	UIView* _realModalAlertView;
}
-(void)layoutSubviews;
-(void)removeAlertView;
-(void)showAlertView:(id)view;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

