/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockScreenNotificationBannerItem.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationSystemBannerItem : SBLockScreenNotificationBannerItem {
}
-(id)_systemListItem;
-(id)unlockActionContext;
-(id)iconImage;
-(id)message;
-(id)title;
@end

