/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBLockScreenBulletinCell.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenPassbookCell : SBLockScreenBulletinCell {
}
@end

