/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayContext.h"


__attribute__((visibility("hidden")))
@interface SBLockScreenPluginOverlayContext : SBLockOverlayContext {
}
-(BOOL)_pluginNeedsOverlay:(id)overlay;
-(id)initWithPluginName:(id)pluginName pluginController:(id)controller lockScreenViewController:(id)controller3;
@end

