/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationTableView : XXUnknownSuperclass {
}
-(void)_setSeparatorBackdropOverlayBlendMode:(int)mode;
-(int)_separatorBackdropOverlayBlendMode;
@end

