/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockScreenNotificationBannerItem.h"

@class SBUISound;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationBulletinBannerItem : SBLockScreenNotificationBannerItem {
	SBUISound* _sound;
}
@property(readonly, retain) SBUISound* sound;
-(id)_bulletinListItem;
-(id)unlockActionContext;
-(BOOL)isVIP;
-(id)attachmentImage;
-(id)attachmentText;
-(id)iconImage;
-(id)sourceDate;
-(id)message;
-(id)title;
-(void)dealloc;
-(id)initWithListItem:(id)listItem;
@end

