/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockScreenViewDelegate <NSObject>
-(void)addCoordinatedPresentingController:(id)controller;
-(void)removeCoordinatedPresentingController:(id)controller;
-(BOOL)wantsToShowStatusBarTime;
-(id)effectiveCustomSlideToUnlockText;
-(BOOL)lockScreenViewPhonePluginIsActive;
-(void)lockScreenView:(id)view didEndScrollingOnPage:(int)page;
-(void)lockScreenViewWillEndDraggingWithPercentScrolled:(float)lockScreenView percentScrolledVelocity:(float)velocity targetScrollPercentage:(float)percentage;
-(void)lockScreenViewDidScrollWithNewScrollPercentage:(float)lockScreenView tracking:(BOOL)tracking;
-(void)lockScreenViewDidBeginScrolling:(id)lockScreenView;
-(void)lockScreenView:(id)view didScrollToPage:(int)page;
@end

