/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBLockScreenTimerViewControllerDelegate
-(void)timerControllerDidStopTimer:(id)timerController;
-(void)timerControllerDidStartTimer:(id)timerController;
@end

