/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenPluginTransitionFactory : XXUnknownSuperclass {
}
-(BOOL)_shouldAnimateContext:(id)context;
-(id)transitionWithContext:(id)context;
@end

