/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDisableAppStatusBarAlphaChangesAssertion;

__attribute__((visibility("hidden")))
@interface SBLockToAppStatusBarAnimator : XXUnknownSuperclass {
	SBDisableAppStatusBarAlphaChangesAssertion* _disableStatusBarAlphaChangeAssertion;
}
-(void)animateStatusBarFromLockToHome;
@end

