/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockScreenPluginControllerDelegate <NSObject>
-(void)pluginController:(id)controller activePluginDidChange:(id)activePlugin;
@end

