/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockOverlayViewControllerDelegate <NSObject>
-(void)overlay:(id)overlay wantsStyleChange:(unsigned)change;
@end

