/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBLockOverlayViewControllerDelegate.h"


@protocol SBLockScreenInfoOverlayDelegate <SBLockOverlayViewControllerDelegate>
-(void)infoOverlayWantsDismissal;
@end

