/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBPasscodeLockDisableAssertion, NSString;

__attribute__((visibility("hidden")))
@interface SBLockScreenDisableAssertion : XXUnknownSuperclass {
	NSString* _identifier;
	SBPasscodeLockDisableAssertion* _disableLockAssertion;
}
+(void)initialize;
-(void)dealloc;
-(id)description;
-(id)initWithIdentifier:(id)identifier;
@end

