/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockScreenNotificationBannerItemDelegate <NSObject>
-(void)bannerItemWasTapped:(id)tapped;
@end

