/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIGestureRecognizerDelegate.h"

@class SBLockScreenNotificationCell;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationScrollView : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
	SBLockScreenNotificationCell* _associatedCell;
}
@property(assign, nonatomic) SBLockScreenNotificationCell* associatedCell;
+(float)scrollThresholdForPasscodeScroll;
@end

