/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIDynamicAnimatorDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "_UISettingsKeyObserver.h"

@class NSSet, UIGestureRecognizer, NSMutableSet, SBBouncingItem, UIView, SBBounceBehavior, SBBounceSettings, SBBouncingSystem, UIDynamicAnimator;
@protocol SBPresentingDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenBounceAnimator : XXUnknownSuperclass <UIDynamicAnimatorDelegate, _UISettingsKeyObserver, UIGestureRecognizerDelegate> {
	NSMutableSet* _tapExcludedViews;
	BOOL _isAnimating;
	BOOL _bounceEnabled;
	UIView* _view;
	SBBouncingSystem* _system;
	UIDynamicAnimator* _animator;
	SBBouncingItem* _item;
	SBBounceBehavior* _behavior;
	UIGestureRecognizer* _tapRecognizer;
	NSSet* _gestures;
	id _shouldBeginBlock;
	id _prepareBlock;
	id _translateBlock;
	id _canceledBlock;
	id _completedBlock;
	SBBounceSettings* _settings;
	id<SBPresentingDelegate> _presentingDelegate;
}
@property(readonly, assign, nonatomic) NSSet* gestures;
@property(assign, nonatomic) id<SBPresentingDelegate> presentingDelegate;
@property(readonly, assign, nonatomic) NSSet* tapExcludedViews;
@property(retain, nonatomic) SBBounceSettings* settings;
@property(copy) id completedBlock;
@property(copy) id canceledBlock;
@property(copy) id translateBlock;
@property(copy) id prepareBlock;
@property(copy) id shouldBeginBlock;
@property(readonly, assign) BOOL isAnimating;
-(void)dynamicAnimatorDidPause:(id)dynamicAnimator;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_updateSettings;
-(void)_createAnimator;
-(void)_removeAnimator;
-(void)_resetAnimator;
-(void)_beginAnimating:(id)animating;
-(void)reenableGestureRecognizer:(id)recognizer;
-(void)cancelGestureRecognizer:(id)recognizer;
-(void)_handleTapGesture:(id)gesture;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(void)_removeTapRecognizer;
-(void)_addTapRecognizer;
-(void)removeTapExcludedView:(id)view;
-(void)addTapExcludedView:(id)view;
-(void)setBounceEnabled:(BOOL)enabled;
-(void)cancelAnimation;
-(void)dealloc;
-(id)initWithView:(id)view;
@end

