/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBLockScreenNotificationListDelegate <NSObject>
-(void)addCoordinatedPresentingController:(id)controller;
-(void)removeCoordinatedPresentingController:(id)controller;
-(void)dismissFullscreenBulletinAlertWithItem:(id)item;
-(void)modifyFullscreenBulletinAlertWithItem:(id)item;
-(void)presentFullscreenBulletinAlertWithItem:(id)item;
-(id)lockScreenScrollView;
-(void)notificationListBecomingVisible:(BOOL)visible;
-(void)attemptToUnlockUIFromNotification;
-(void)bannerEnablementChanged;
@end

