/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBLSApplicationLifecycleObserver
-(void)applicationsInstalled:(id)installed;
-(void)applicationsUninstalled:(id)uninstalled;
@end

