/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconLabelImageParameters.h"

@class NSString, UIColor, UIFont;

__attribute__((visibility("hidden")))
@interface SBMutableIconLabelImageParameters : SBIconLabelImageParameters {
}
@property(assign, nonatomic) UIEdgeInsets textInsets;
@property(retain, nonatomic) UIColor* focusHighlightColor;
@property(assign, nonatomic) BOOL accessibilityIncreaseContrastEnabled;
@property(retain, nonatomic) UIColor* textColor;
@property(assign, nonatomic) int style;
@property(assign, nonatomic) BOOL canUseMemoryPool;
@property(assign, nonatomic) BOOL canEllipsize;
@property(assign, nonatomic) BOOL containsEmoji;
@property(assign, nonatomic) BOOL containsNonLatinLikeCharacters;
@property(assign, nonatomic) float scale;
@property(retain, nonatomic) UIFont* font;
@property(assign, nonatomic) CGSize maxSize;
@property(copy, nonatomic) NSString* text;
-(id)copy;
@end

