/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUnlockActionContext.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBMutableUnlockActionContext : SBUnlockActionContext {
}
@property(assign, nonatomic) BOOL canBypassPinLock;
@property(assign, nonatomic) BOOL deactivateAwayController;
@property(assign, nonatomic) BOOL requiresUnlock;
@property(copy, nonatomic) id unlockAction;
@property(retain, nonatomic) NSString* shortLockLabel;
@property(retain, nonatomic) NSString* lockLabel;
@property(retain, nonatomic) NSString* identifier;
@end

