/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderIcon.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandIcon : SBFolderIcon {
}
-(BOOL)hasFolderIconView;
-(BOOL)isNewsstandIcon;
-(id)getUnmaskedIconImage:(int)image;
-(id)generateIconImage:(int)image;
-(id)_generateImageUsingMask:(BOOL)mask;
-(id)_newsstandIconImageName;
-(id)folder;
-(void)launchFromLocation:(int)location;
-(id)displayName;
@end

