/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconImageView.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandItemIconImageView : SBIconImageView {
}
+(float)cornerRadius;
+(int)_defaultIconFormat;
-(CGRect)visibleBounds;
-(CGSize)sizeThatFits:(CGSize)fits;
-(id)squareDarkeningOverlayImage;
-(id)darkeningOverlayImage;
-(id)_generateSquareContentsImage;
-(id)contentsImage;
@end

