/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBGradientView.h"

@class UIView, SBHighlightView, UIColor;

__attribute__((visibility("hidden")))
@interface SBNewsstandShelfView : SBGradientView {
	UIView* _tintView;
	float _tintAlpha;
	SBHighlightView* _highlightView;
	unsigned _shelfIndex;
}
@property(assign, nonatomic) unsigned shelfIndex;
@property(assign, nonatomic) float tintAlpha;
@property(retain, nonatomic) UIColor* tintColor;
-(void)layoutSubviews;
-(void)dealloc;
@end

