/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconView.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandItemIconView : SBIconView {
}
+(CGSize)defaultIconSize;
+(int)_defaultIconFormat;
-(CGRect)_frameForUpdatedMarkWithLabelFrame:(CGRect)labelFrame;
-(CGRect)_baseFrameForUpdatedMarkWithLabelFrame:(CGRect)labelFrame;
-(CGRect)_frameForLabel;
-(CGRect)_baseFrameForLabel;
-(CGRect)_frameForImageView;
-(CGRect)_baseFrameForImageView;
-(BOOL)_showsShadow;
-(id)initWithFrame:(CGRect)frame;
@end

