/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFolderController.h"


__attribute__((visibility("hidden")))
@interface SBNewsstandFolderController : SBFolderController {
}
+(Class)listViewClass;
-(id)_statusBarColor;
-(id)legibilitySettings;
-(unsigned)_depth;
-(Class)_contentViewClass;
@end

