/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BBRemoteDataProvider.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class BBSectionInfo;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterDataProvider : XXUnknownSuperclass <BBRemoteDataProvider> {
	BBSectionInfo* _sectionInfo;
}
+(id)notificationCenterDataProviderWithSectionInfo:(id)sectionInfo;
-(id)bulletinsWithRequestParameters:(id)requestParameters lastCleared:(id)cleared;
-(id)sortDescriptors;
-(id)defaultSectionInfo;
-(id)sectionIdentifier;
-(void)dealloc;
-(id)initWithSectionInfo:(id)sectionInfo;
@end

