/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBNotificationsClearButton : XXUnknownSuperclass {
	int _graphicsQuality;
}
@property(readonly, assign, nonatomic) int graphicsQuality;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(id)initWithImage:(id)image graphicsQuality:(int)quality;
@end

