/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterDataProviderController : XXUnknownSuperclass {
	NSArray* _dataProviders;
}
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
-(void)buddyCompleted:(id)completed;
-(void)publishSectionInfoIfNecessary;
-(id)_widgetSections;
-(id)_sectionWithIdentifier:(id)identifier forCategory:(int)category;
-(id)_sectionForWidgetBundle:(id)widgetBundle forCategory:(int)category;
-(id)_copyDefaultEnabledWidgetIDs;
-(void)dealloc;
-(id)init;
@end

