/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNotificationsSectionInfo.h"


__attribute__((visibility("hidden")))
@interface SBNotificationsMissedModeSectionInfo : SBNotificationsSectionInfo {
}
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(Class)reusableViewClass;
-(int)sectionCategory;
-(id)identifier;
@end

