/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBNotificationsBulletinInfo.h"


__attribute__((visibility("hidden")))
@interface SBNotificationsAllModeBulletinInfo : SBNotificationsBulletinInfo {
}
-(void)populateReusableView:(id)view;
@end

