/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBNotificationCenterSeparatorView, SBNotificationsClearButton, UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBNotificationsSectionHeaderView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UIImageView* _iconImageView;
	SBNotificationsClearButton* _xButton;
	SBNotificationsClearButton* _clearButton;
	id _xAction;
	id _clearAction;
	BOOL _showingClear;
	SBNotificationCenterSeparatorView* _separator;
	float _clearButtonDescender;
}
@property(readonly, assign, getter=isShowingClear) BOOL showingClear;
+(void)_compositingFilterForView:(id)view;
+(id)defaultBackgroundColorForGraphicsQuality:(int)graphicsQuality;
-(void)buttonAction:(id)action;
-(void)layoutSubviews;
-(void)resetAnimated:(BOOL)animated;
-(void)_setShowsClear:(BOOL)clear animated:(BOOL)animated;
-(CGRect)_clearButtonFrame;
-(CGRect)_xButtonFrame;
-(CGRect)contentBounds;
-(void)setTarget:(id)target forClearButtonAction:(id)clearButtonAction;
-(void)setTarget:(id)target forClearButtonVisibleAction:(id)clearButtonVisibleAction;
-(void)setHasClearButton:(BOOL)button;
-(void)_removeClearButtons;
-(void)_addClearButtons;
-(id)_clearImage;
-(id)_circleXImage;
-(void)setFloating:(BOOL)floating;
-(void)prepareForReuse;
-(void)setBackgroundView:(id)view;
-(int)initialGraphicsQuality;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

