/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIDynamicAnimatorDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class _SBNotificationCenterBouncingItem, SBBounceBehavior, SBBounceSettings, UIDynamicAnimator, SBBouncingSystem;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterBounceAnimator : XXUnknownSuperclass <UIDynamicAnimatorDelegate> {
	UIDynamicAnimator* _animator;
	SBBouncingSystem* _system;
	SBBounceBehavior* _behavior;
	_SBNotificationCenterBouncingItem* _item;
	id _completion;
	SBBounceSettings* _settings;
	CGRect _targetFrame;
}
@property(copy, nonatomic, getter=_completion, setter=_setCompletion:) id completion;
@property(retain, nonatomic, getter=_behavior, setter=_setBehavior:) SBBounceBehavior* behavior;
@property(readonly, assign, nonatomic, getter=_animator) UIDynamicAnimator* animator;
-(void)dynamicAnimatorDidPause:(id)dynamicAnimator;
-(void)_updateSettings;
-(void)beginBounceWithInitialFrame:(CGRect)initialFrame targetFrame:(CGRect)frame velocity:(CGPoint)velocity removingGravityAtMidway:(BOOL)midway stepper:(id)stepper completion:(id)completion;
-(void)dealloc;
-(id)initWithReferenceBounds:(CGRect)referenceBounds settings:(id)settings;
@end

