/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWidgetViewControllerHostDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBBulletinActionHandler.h"


@protocol SBNotificationCenterViewControllerDelegate <SBWidgetViewControllerHostDelegate, SBBulletinActionHandler>
@optional
-(id)widgetViewControllerHostDelegate:(id)delegate;
@end

