/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"

@class SBBulletinListSection;

__attribute__((visibility("hidden")))
@interface SBNotificationsSectionInfo : SBBBSectionInfo {
	id _clearPossibleAction;
	id _clearAction;
}
@property(copy, nonatomic) id clearAction;
@property(copy, nonatomic) id clearPossibleAction;
@property(readonly, assign, nonatomic) SBBulletinListSection* representedListSection;
-(void)populateReusableView:(id)view;
-(BOOL)shouldSuppressBulletinMessageForPrivacy:(id)privacy;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(Class)reusableViewClass;
-(id)identifier;
-(void)dealloc;
@end

