/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBPasscodeEntryAlertViewController;

__attribute__((visibility("hidden")))
@interface SBPasscodeAlertRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBPasscodeEntryAlertViewController* _alert;
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)dealloc;
@end

