/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface SBPieChartView : XXUnknownSuperclass {
	NSArray* _slices;
	float _valueTotal;
	float _radius;
	CGPoint _center;
	float _defaultRotation;
}
-(void)_drawSlice:(id)slice atValue:(float)value;
-(void)_rotateContext;
-(void)_updateMetrics;
-(void)drawRect:(CGRect)rect;
-(void)setSlices:(id)slices;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

