/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIcon.h"


__attribute__((visibility("hidden")))
@interface SBPlaceholderIcon : SBIcon {
	id _nodeIdentifier;
	SBIcon* _icon;
}
@property(readonly, retain) id nodeIdentifier;
+(id)emptyPlaceholder;
+(void)setGrabbedIcon:(id)icon;
+(id)grabbedIconPlaceholder;
+(id)placeholderForIcon:(id)icon;
+(id)placeholderNodeIdentifierForIcon:(id)icon;
-(id)referencedIcon;
-(BOOL)isEmptyPlaceholder;
-(BOOL)isGrabbedIconPlaceholder;
-(BOOL)isPlaceholder;
-(BOOL)shouldCacheImageForFormat:(int)format;
-(id)generateIconImage:(int)image;
-(id)automationID;
-(void)dealloc;
-(id)_initWithNodeIdentifier:(id)nodeIdentifier icon:(id)icon;
@end

