/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@protocol SBPowerDownViewDelegate;

@protocol SBPowerDownViewInterface <NSObject>
@property(assign, nonatomic) id<SBPowerDownViewDelegate> delegate;
-(void)animateOut;
-(void)animateIn;
@end

