/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBPowerDownControllerDelegate <NSObject>
-(void)powerDownCanceled:(id)canceled;
-(void)powerDownRequested:(id)requested;
@end

