/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"


__attribute__((visibility("hidden")))
@interface SBPPTAlertViewDelegate : XXUnknownSuperclass <UIAlertViewDelegate> {
}
-(void)didPresentAlertView:(id)view;
@end

