/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBPushStoreObserver <NSObject>
-(void)pushStoreUserDeclinedDelivery;
-(void)pushStoreUserAcceptedDelivery;
-(void)pushStoreUpdatedPushSettings;
-(void)pushStoreClearedNotifications;
-(void)pushStoreNotificationsDidChange;
@end

