/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "_SBRemoteAlertHostViewControllerDelegate.h"
#import "SBAlertAdapter.h"

@class NSString, _SBRemoteAlertHostViewController;

__attribute__((visibility("hidden")))
@interface SBRemoteAlertAdapter : SBAlertAdapter <_SBRemoteAlertHostViewControllerDelegate> {
	_SBRemoteAlertHostViewController* _remoteAlertHostViewController;
	NSString* _impersonatedApplicationBundleID;
	BOOL _activated;
	BOOL _dismissWithHomeButton;
}
+(void)requestRemoteViewService:(id)service options:(id)options completion:(id)completion;
-(BOOL)isRemote;
-(BOOL)matchesRemoteAlertService:(id)service options:(id)options;
-(void)remoteAlertDidTerminateWithError:(id)remoteAlert;
-(void)remoteAlertWantsToAllowBanners:(BOOL)allowBanners;
-(void)_setImpersonatedApplicationBundleID:(id)anId;
-(void)_setDismissWithHomeButton:(BOOL)homeButton;
-(BOOL)handleMenuButtonTap;
-(void)deactivate;
-(void)activate;
-(id)_impersonatesApplicationWithBundleID;
-(void)dealloc;
-(id)initWithViewController:(id)viewController;
-(id)_initWithRemoteAlertHostViewController:(id)remoteAlertHostViewController;
@end

