/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSCalendar, NSDate, NSTimer;
@protocol SBRelativeDateTimerDelegate;

__attribute__((visibility("hidden")))
@interface SBRelativeDateTimer : XXUnknownSuperclass {
	NSCalendar* _gregorian;
	NSTimer* _timer;
	NSDate* _date;
	id<SBRelativeDateTimerDelegate> _delegate;
	int _currResolution;
	int _currValue;
}
@property(retain) NSDate* date;
+(void)invalidateTimer:(id)timer;
+(void)addTimerToMainRunLoop:(id)mainRunLoop;
+(void)initialize;
-(double)_nextFireInterval:(id)interval resolution:(int)resolution comparedToNow:(int)now;
-(void)_fireAndUpdateTimerIfNecessary;
-(id)_timeDifferenceFromDate:(id)date;
-(void)invalidate;
-(void)fireAndSchedule;
-(double)nextFireInterval;
-(void)setDelegate:(id)delegate;
-(void)_fireForLocaleEvent:(id)localeEvent;
-(void)_fireForEvent:(id)event;
-(void)dealloc;
-(id)init;
@end

