/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBRestoreFailureAlertItem : XXUnknownSuperclass {
}
-(BOOL)allowInSetup;
-(BOOL)forcesModalAlertAppearance;
-(BOOL)shouldShowInLockScreen;
-(BOOL)allowMenuButtonDismissal;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)performUnlockAction;
-(void)restartSystemEvent;
-(void)_rebootNow;
-(double)autoDismissInterval;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
@end

