/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBHomeScreenNagAlert.h"


__attribute__((visibility("hidden")))
@interface SBReorderInfoAlert : SBHomeScreenNagAlert {
}
-(void)didDeactivateForReason:(int)reason;
@end

