/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface SBRoundedRectBorderView : XXUnknownSuperclass {
}
@property(assign, nonatomic) float cornerRadius;
@property(assign, nonatomic) float borderWidth;
@property(retain, nonatomic) UIColor* borderColor;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

