/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBReducedMotionFadeSettings, SBUnlockSettings, SBCenterAppLaunchSettings, SBCenterAppSuspendSettings, SBCrossfadeAppLaunchSettings, SBCrossfadeAppSuspendSettings, SBFolderOpenSettings, SBFolderCloseSettings;

__attribute__((visibility("hidden")))
@interface SBRootAnimationSettings : XXUnknownSuperclass {
	SBReducedMotionFadeSettings* _reducedMotionSettings;
	SBUnlockSettings* _unlockSettings;
	SBCenterAppLaunchSettings* _centerLaunchSettings;
	SBCenterAppSuspendSettings* _centerSuspendSettings;
	SBCrossfadeAppLaunchSettings* _crossfadeLaunchSettings;
	SBCrossfadeAppSuspendSettings* _crossfadeSuspendSettings;
	SBFolderOpenSettings* _folderOpenSettings;
	SBFolderCloseSettings* _folderCloseSettings;
}
@property(retain) SBFolderCloseSettings* folderCloseSettings;
@property(retain) SBFolderOpenSettings* folderOpenSettings;
@property(retain) SBCrossfadeAppSuspendSettings* crossfadeSuspendSettings;
@property(retain) SBCrossfadeAppLaunchSettings* crossfadeLaunchSettings;
@property(retain) SBCenterAppSuspendSettings* centerSuspendSettings;
@property(retain) SBCenterAppLaunchSettings* centerLaunchSettings;
@property(retain) SBUnlockSettings* unlockSettings;
@property(retain) SBReducedMotionFadeSettings* reducedMotionSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

