/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconZoomAnimator.h"

@class SBIconView, SBIcon, UIView, SBScaleZoomSettings;

__attribute__((visibility("hidden")))
@interface SBScaleIconZoomAnimator : SBIconZoomAnimator {
	UIEdgeInsets _iconScootch;
	float _dockStretch;
	SBIconCoordinate _dockListCenterCoordinate;
	SBIconCoordinate _mainListCenterCoordinate;
	float _naturalVisualAltitude;
	UIView* _scalingView;
	SBIcon* _targetIcon;
	float _zoomScale;
}
@property(readonly, assign, nonatomic) float zoomScale;
@property(readonly, assign, nonatomic) SBIconView* targetIconView;
@property(readonly, assign, nonatomic) SBIcon* targetIcon;
@property(retain, nonatomic) SBScaleZoomSettings* settings;
-(void)_calculateIconScootch;
-(CGPoint)_scootchForIcon:(id)icon inDock:(BOOL)dock;
-(void)_applyOuterFadeFraction:(float)fraction;
-(void)_applyZoomFraction:(float)fraction;
-(float)_zoomedVisualAltitude;
-(CGPoint)_zoomedIconCenter;
-(CGRect)_zoomedFrame;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController targetIcon:(id)icon;
@end

