/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBScreenConnectionHandler <NSObject>
-(void)screenManager:(id)manager didTriggerConnectionHandlerEvent:(int)event forScreen:(id)screen;
-(BOOL)screenManager:(id)manager shouldBindConnectionHandlerToScreen:(id)screen;
@end

