/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWallpaperEffectView, UIView, _UIBackdropView;

__attribute__((visibility("hidden")))
@interface SBSearchResultsBackdropView : XXUnknownSuperclass {
	_UIBackdropView* _backdropView;
	SBWallpaperEffectView* _effectView;
	UIView* _tintView;
}
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

