/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBSearchGestureObserver <NSObject>
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
@optional
-(void)searchGesture:(id)gesture completedShowing:(BOOL)showing;
@end

