/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString, UIView;

__attribute__((visibility("hidden")))
@interface SBSearchTableHeaderView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UIView* _separatorView;
	NSString* _reuseIdentifier;
}
@property(readonly, assign, nonatomic) NSString* reuseIdentifier;
@property(retain, nonatomic) NSString* title;
+(id)lineColor;
+(float)heightForActiveContentSizeCategory;
-(BOOL)isUserInteractionEnabled;
-(void)dealloc;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
@end

