/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBApplication, SBProxyRemoteView, SBFakeStatusBarView;

__attribute__((visibility("hidden")))
@interface SBSheetView : XXUnknownSuperclass {
	SBProxyRemoteView* _remoteProxyView;
	SBApplication* _app;
	SBFakeStatusBarView* _fakeStatusBarView;
	BOOL _wasPresentedAnimated;
}
@property(readonly, retain) SBFakeStatusBarView* fakeStatusBarView;
@property(readonly, assign) BOOL wasPresentedAnimated;
-(void)dealloc;
-(void)noteSheetDidEnd;
-(id)application;
-(id)remoteViewIdentifier;
-(id)initWithRemoteViewIdentifier:(id)remoteViewIdentifier application:(id)application shouldFakeStatusBar:(BOOL)bar wasPresentedAnimated:(BOOL)animated;
@end

