/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBShapeView : XXUnknownSuperclass {
}
+(Class)layerClass;
-(id)_shapeLayer;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(void)setFillRule:(int)rule;
-(void)setFillColor:(id)color;
-(void)setPath:(id)path;
@end

