/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFileLogger.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBSimplePreferenceFileLogger : SBFileLogger {
	BOOL _enabled;
}
@property(readonly, assign, nonatomic) NSString* logPreferenceName;
@property(readonly, assign, nonatomic) NSString* logPreferenceDomain;
@property(readonly, assign, getter=isEnabled) BOOL enabled;
-(void)reloadFromDefaults;
@end

