/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBSIMLockEntryAlert : SBAlert {
	int _status;
}
@property(readonly, assign) int status;
-(void)deactivate;
-(void)activate;
-(id)lockEntryView;
-(BOOL)hasTranslucentBackground;
-(id)alertDisplayViewWithSize:(CGSize)size;
@end

