/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBSIMLockEntryAlert;

__attribute__((visibility("hidden")))
@interface SBSIMLockPasscodeRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBSIMLockEntryAlert* _alert;
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

