/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol SBSizeObservingViewDelegate <NSObject>
-(void)sizeObservingView:(id)view didChangeSize:(CGSize)size;
@end

