/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUSSDAlert.h"


__attribute__((visibility("hidden")))
@interface SBSMSClass0Alert : SBUSSDAlert {
}
+(void)playMessageReceived;
+(void)registerForAlerts;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(void)deactivate;
-(id)_initWithString:(id)string;
-(void)_registerForNotifications;
-(void)_unregisterForNotifications;
@end

