/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAwayBulletinListItem.h"


__attribute__((visibility("hidden")))
@interface SBSnoozedAlarmBulletinListItem : SBAwayBulletinListItem {
}
-(BOOL)canBeClearedByNotificationCenter;
-(id)sortDate;
@end

