/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBBBBulletinInfo.h"

@class UIImage, SBItemInfoLayoutCache;

__attribute__((visibility("hidden")))
@interface SBSnippetBulletinInfo : SBBBBulletinInfo {
	CGRect _textRect;
	UIImage* _icon;
	SBItemInfoLayoutCache* _layoutCache;
}
@property(retain, nonatomic) UIImage* icon;
+(float)topBaselineToCellTopInLayoutMode:(int)layoutMode;
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(id)_representedBulletin;
-(void)invalidateCachedLayoutData;
-(Class)reusableViewClass;
-(id)identifier;
-(void)dealloc;
@end

