/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIScreen;

__attribute__((visibility("hidden")))
@interface SBSnapshotImageInfo : XXUnknownSuperclass {
	BOOL _defaultPNG;
	NSString* _path;
	NSString* _downscaledPath;
	UIScreen* _screen;
	float _scale;
	int _launchingOrientation;
	int _originalOrientation;
}
@property(assign, nonatomic) BOOL defaultPNG;
@property(assign, nonatomic) int originalOrientation;
@property(assign, nonatomic) int launchingOrientation;
@property(assign, nonatomic) float scale;
@property(retain, nonatomic) UIScreen* screen;
@property(copy, nonatomic) NSString* downscaledPath;
@property(copy, nonatomic) NSString* path;
+(id)snapshotImageInfoWithPath:(id)path downscaledPath:(id)path2 launchingOrientation:(int)orientation originalOrientation:(int)orientation4 forScreen:(id)screen;
-(id)description;
-(id)_stringForInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
@end

