/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBScreenConnectionHandler.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBLockScreenDisableAssertion, NSMapTable, SBPasscodeLockDisableAssertion, SBSpuriousScreenUndimmingAssertion, SBStarkScreenController, SBStarkStatusBarStateProvider;
@protocol SBStarkScreenManagerDelegate;

__attribute__((visibility("hidden")))
@interface SBStarkScreenManager : XXUnknownSuperclass <SBScreenConnectionHandler> {
	NSMapTable* _screenToControllerMap;
	SBStarkScreenController* _currentScreenController;
	SBStarkStatusBarStateProvider* _statusBarStateProvider;
	SBSpuriousScreenUndimmingAssertion* _spuriousScreenUndimmingAssertion;
	SBPasscodeLockDisableAssertion* _deviceLockDisableAssertion;
	SBLockScreenDisableAssertion* _lockScreenDisableAssertion;
	BOOL _geoSupported;
	id<SBStarkScreenManagerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBStarkScreenManagerDelegate> delegate;
@property(readonly, retain) SBStarkScreenController* currentScreenController;
@property(readonly, retain) SBStarkStatusBarStateProvider* statusBarStateProvider;
@property(readonly, assign, getter=isGeoSupported) BOOL geoSupported;
+(id)sharedInstance;
-(void)screenManager:(id)manager didTriggerConnectionHandlerEvent:(int)event forScreen:(id)screen;
-(BOOL)screenManager:(id)manager shouldBindConnectionHandlerToScreen:(id)screen;
-(void)_promptConnectionSteps;
-(void)_setCurrentController:(id)controller;
-(void)_updateGeoSupport;
-(void)_setGeoSupported:(BOOL)supported;
-(BOOL)isStarkActive;
-(id)activeScreenController;
-(BOOL)starkScreenIsAttached;
-(void)dealloc;
-(id)init;
@end

