/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray, UIScreen;

__attribute__((visibility("hidden")))
@interface SBStarkScreenFocusController : XXUnknownSuperclass {
	UIScreen* _screen;
	NSMutableArray* _assertions;
	NSString* _displayID;
}
-(id)description;
-(id)focusWindow;
-(void)dropReason:(id)reason;
-(void)takeWithPriority:(float)priority reason:(id)reason forWindow:(id)window bundleIdentifier:(id)identifier;
-(void)invalidate;
-(void)_applyAssertion:(id)assertion;
-(void)_updateEventFocus;
-(void)dealloc;
-(id)initWithScreen:(id)screen;
@end

