/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIStatusBarStyleDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIStatusBar, NSMutableSet, UIView;

__attribute__((visibility("hidden")))
@interface SBStarkStatusBarViewController : XXUnknownSuperclass <UIStatusBarStyleDelegate> {
	UIStatusBar* _statusBarView;
	id<UIStatusBarStyleDelegate> _statusBarStyleDelegate;
	int _layoutJustification;
	NSMutableSet* _statusBarHideReasons;
	int _requestedStyle;
	BOOL _styleHasBeenRequested;
	float _statusBarWidth;
	UIView* _separatorView;
	BOOL _separatorHidden;
}
@property(assign, nonatomic, getter=isSeparatorHidden) BOOL separatorHidden;
@property(assign, nonatomic) int layoutJustification;
@property(assign, nonatomic) id<UIStatusBarStyleDelegate> statusBarStyleDelegate;
-(void)statusBar:(id)bar didTriggerButtonType:(int)type withAction:(int)action;
-(void)statusBar:(id)bar didAnimateFromHeight:(float)height toHeight:(float)height3 animation:(int)animation;
-(void)statusBar:(id)bar willAnimateFromHeight:(float)height toHeight:(float)height3 duration:(double)duration animation:(int)animation;
-(int)statusBar:(id)bar styleForRequestedStyle:(int)requestedStyle overrides:(int)overrides;
-(BOOL)_isStatusBarHidden;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)_layoutStatusBar:(id)bar;
-(id)newFakeStatusBarWithStyle:(int)style;
-(id)newFakeStatusBar;
-(void)updateStatusBarWithRequestedStyle:(int)requestedStyle animationFactory:(id)factory;
-(void)setStatusBarHidden:(BOOL)hidden forReason:(id)reason withAnimationFactory:(id)animationFactory;
-(void)dealloc;
@end

