/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBAlertItemsControllerObserver.h"
#import "SBStarkBannerSource.h"


__attribute__((visibility("hidden")))
@interface SBStarkAlertItemBannerSource : SBStarkBannerSource <SBAlertItemsControllerObserver> {
}
-(void)alertItemsController:(id)controller didDeactivateAlertItem:(id)item forReason:(int)reason;
-(void)alertItemsController:(id)controller didActivateAlertItem:(id)item;
-(void)alertItemsController:(id)controller willActivateAlertItem:(id)item;
-(void)dealloc;
-(id)initWithAllowedTargetIdentifier:(void*)allowedTargetIdentifier;
@end

