/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface SBStarkRelockUIViewController : XXUnknownSuperclass {
	UILabel* _label;
}
-(void)viewDidLoad;
-(void)dealloc;
@end

