/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBVolumePressBandit.h"
#import "BBObserverDelegate.h"
#import "SBStarkBannerSource.h"

@class BBObserver;

__attribute__((visibility("hidden")))
@interface SBStarkBulletinBannerSource : SBStarkBannerSource <BBObserverDelegate, SBVolumePressBandit> {
	BBObserver* _bbObserver;
}
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)_reloadVolumePressBanditPreference;
-(void)observer:(id)observer noteServerReceivedResponseForBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)_showTestBanner:(id)banner;
-(void)dealloc;
-(id)initWithAllowedTargetIdentifier:(void*)allowedTargetIdentifier;
@end

