/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconImageView.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconImageView : SBIconImageView {
}
+(float)cornerRadius;
@end

