/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBTestStarkAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAlertRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBTestStarkAlert* _alert;
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

