/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWindow.h"
#import "SBStarkNotificationViewControllerDelegate.h"

@class SBStarkNotificationViewController, SBStarkScreenFocusController;

__attribute__((visibility("hidden")))
@interface SBStarkNotificationWindow : SBWindow <SBStarkNotificationViewControllerDelegate> {
	SBStarkScreenFocusController* _focusController;
	id _borrowScreenToken;
}
@property(retain, nonatomic) SBStarkNotificationViewController* rootViewController;
@property(retain, nonatomic) SBStarkScreenFocusController* focusController;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)notificationViewController:(id)controller stateDidChangeFrom:(int)state;
-(void)dealloc;
-(id)initWithScreen:(id)screen jailBehavior:(int)behavior;
@end

