/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBStarkNowPlayingServiceDelegate <NSObject>
-(void)nowPlayingService:(id)service didTerminateWithError:(id)error;
@end

