/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconBadgeView.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconBadgeView : SBIconBadgeView {
}
+(id)_checkoutBackgroundImage;
+(CGPoint)_overhang;
+(float)_textPadding;
+(CGPoint)_textOffset;
+(float)_maxTextWidth;
+(id)_textFont;
@end

