/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListPageControl.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconListPageControl : SBIconListPageControl {
}
-(float)_indicatorSpacing;
-(id)_iconListIndicatorImage:(BOOL)image;
@end

