/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconListModel.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconListModel : SBIconListModel {
}
+(unsigned)maxIcons;
-(BOOL)allowsAddingIcon:(id)icon;
@end

