/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBStarkScreenControllerDelegate <NSObject>
-(void)starkScreenController:(id)controller didChangeStateFromState:(int)state;
@end

