/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBCollectionViewCell.h"
#import "SBUIBannerView.h"

@class SBBannerContextView, UIView;

__attribute__((visibility("hidden")))
@interface SBStarkBannerCell : SBCollectionViewCell <SBUIBannerView> {
	SBBannerContextView* _contextView;
	UIView* _darkeningOverlayView;
}
@property(retain) id bannerContext;
-(void)prepareForReuse;
-(void)noteDidDismiss;
-(void)noteWillDismissWithReason:(int)note;
-(void)noteDidAppear;
-(void)noteWillAppear;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

