/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBStarkScreenManagerDelegate <NSObject>
-(void)starkScreenManagerDidChangeActiveController:(id)starkScreenManager;
-(void)starkScreenManagerWillChangeActiveController:(id)starkScreenManager;
@end

