/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkFolderController.h"


__attribute__((visibility("hidden")))
@interface SBStarkRootFolderController : SBStarkFolderController {
}
+(Class)listViewClass;
@end

