/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconModelApplicationDataSource.h"


__attribute__((visibility("hidden")))
@interface SBStarkIconModelApplicationDataSource : XXUnknownSuperclass <SBIconModelApplicationDataSource> {
}
-(id)firstPageLeafIdentifiers;
-(BOOL)isNewsstandEnabled;
-(BOOL)isNewsstandSupported;
-(id)defaultIconState;
-(int)appVisibilityOverrideForBundleIdentifier:(id)bundleIdentifier;
-(BOOL)updateAppIconVisibilityOverridesShowing:(id*)showing hiding:(id*)hiding;
-(id)allApplications;
@end

