/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWindow.h"


__attribute__((visibility("hidden")))
@interface SBStarkDefaultHostingWindow : SBWindow {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

