/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "SBCollectionViewCellDelegate.h"
#import "SBStarkBannerTargetObserver.h"

@class SBStarkBulletinBannerSource, SBStarkBannerCell, SBStarkNotificationLayout, SBStarkAlertItemBannerSource, SBStarkBannerTarget, UITapGestureRecognizer, NSArray, SBCarBannerNotificationView, SBUIBannerContext;
@protocol SBStarkNotificationViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBStarkNotificationViewController : XXUnknownSuperclass <UICollectionViewDataSource, UICollectionViewDelegate, SBCollectionViewCellDelegate, SBStarkBannerTargetObserver, UIGestureRecognizerDelegate> {
	id<SBStarkNotificationViewControllerDelegate> _delegate;
	BOOL _touchCapable;
	UITapGestureRecognizer* _backGestureRecognizer;
	UITapGestureRecognizer* _selectGestureRecognizer;
	SBStarkBannerTarget* _bannerTarget;
	SBStarkAlertItemBannerSource* _alertItemBannerSource;
	SBStarkBulletinBannerSource* _bulletinBannerSource;
	SBUIBannerContext* _currentContext;
	NSArray* _currentSubActionLabels;
	SBStarkBannerCell* _currentCell;
	int _state;
	SBStarkNotificationLayout* _notificationsLayout;
	SBCarBannerNotificationView* _notificationsView;
}
@property(assign, nonatomic) int state;
@property(assign, nonatomic) id<SBStarkNotificationViewControllerDelegate> delegate;
-(void)starkBannerTarget:(id)target didChangeContextWithDismissReason:(int)dismissReason;
-(void)_performSelectGesture:(id)gesture;
-(void)_performBackGesture:(id)gesture;
-(void)collectionView:(id)view didEndDisplayingCell:(id)cell forItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;
-(BOOL)collectionView:(id)view shouldDeselectItemAtIndexPath:(id)indexPath;
-(BOOL)collectionView:(id)view shouldSelectItemAtIndexPath:(id)indexPath;
-(BOOL)collectionView:(id)view shouldHighlightItemAtIndexPath:(id)indexPath;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)numberOfSectionsInCollectionView:(id)collectionView;
-(BOOL)isSuspended;
-(void)setSuspended:(BOOL)suspended cancellingCurrent:(BOOL)current forReason:(id)reason;
-(void)setSuspended:(BOOL)suspended forReason:(id)reason;
-(void)dismissCurrent;
-(void)_setState:(int)state;
-(void)loadView;
-(void)dealloc;
-(id)initWithInteractionAffordances:(unsigned)interactionAffordances;
@end

