/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkBannerItem.h"

@class SBAlertItem, NSString, NSDate, SBUISound;

__attribute__((visibility("hidden")))
@interface SBStarkAlertItemBannerItem : SBStarkBannerItem {
	SBAlertItem* _alertItem;
	NSString* _title;
	NSString* _message;
	SBUISound* _sound;
	NSDate* _originDate;
}
@property(readonly, retain) NSString* title;
@property(readonly, retain) SBUISound* sound;
-(id)subActionWithIndex:(unsigned)index;
-(id)subActionLabels;
-(id)sourceDate;
-(id)ignoreAction;
-(id)action;
-(BOOL)isSticky;
-(unsigned)priority;
-(BOOL)matchesContext:(id)context;
-(void)reloadDisplayProperties;
-(int)defaultActionType;
-(id)categoryImage;
-(id)category;
-(void)dealloc;
-(id)initWithAlertItem:(id)alertItem;
@end

