/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkWorkspaceTransaction.h"


__attribute__((visibility("hidden")))
@interface SBStarkConnectWorkspaceTransaction : SBStarkWorkspaceTransaction {
}
-(void)_commit;
@end

