/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBWindow.h"

@class SBStarkStatusBarViewController;

__attribute__((visibility("hidden")))
@interface SBStarkStatusBarWindow : SBWindow {
}
@property(retain, nonatomic) SBStarkStatusBarViewController* rootViewController;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

