/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBStarkIconLayoutOverrideStrategy : XXUnknownSuperclass {
	UIEdgeInsets _layoutInsets;
	BOOL _preservesCurrentListOrigin;
}
@property(readonly, assign, nonatomic) BOOL preservesCurrentListOrigin;
@property(readonly, assign, nonatomic) UIEdgeInsets layoutInsets;
-(id)initWithNonJailedOverrideStrategy:(id)nonJailedOverrideStrategy;
@end

