/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWindow.h"
#import "SBWindowContextManagerDelegate.h"
#import "SBWindowContextHostManagerDelegate.h"

@class SBWindowContextHostManager, SBWindowContextManager;

__attribute__((visibility("hidden")))
@interface SBStarkNowPlayingWindow : SBWindow <SBWindowContextManagerDelegate, SBWindowContextHostManagerDelegate> {
	SBWindowContextManager* _contextManager;
	SBWindowContextHostManager* _contextHostManager;
}
@property(readonly, retain) SBWindowContextHostManager* contextHostManager;
-(void)windowContextManager:(id)manager didStopTrackingContextsForScreen:(id)screen;
-(void)windowContextManager:(id)manager willStartTrackingContextsForScreen:(id)screen;
-(BOOL)windowContextManager:(id)manager shouldAddContext:(id)context;
-(void)dealloc;
-(id)initWithScreen:(id)screen jailBehavior:(int)behavior;
@end

