/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIWindow, NSString;

__attribute__((visibility("hidden")))
@interface SBStarkScreenFocusAssertion : XXUnknownSuperclass {
	NSString* _name;
	int _type;
	float _priority;
	UIWindow* _window;
	NSString* _bundleID;
}
@property(readonly, assign, nonatomic) NSString* bundleID;
@property(readonly, assign, nonatomic) UIWindow* window;
@property(readonly, assign, nonatomic) float priority;
@property(readonly, assign, nonatomic) int type;
@property(readonly, assign, nonatomic) NSString* name;
-(id)description;
-(void)dealloc;
-(id)initWithName:(id)name type:(int)type priority:(float)priority window:(id)window application:(id)application;
@end

