/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkBannerItem.h"

@class SBUISound, BBBulletin;

__attribute__((visibility("hidden")))
@interface SBStarkBulletinBannerItem : SBStarkBannerItem {
	BBBulletin* _bulletin;
	SBUISound* _sound;
	unsigned _feed;
}
@property(readonly, retain) SBUISound* sound;
-(id)subActionWithIndex:(unsigned)index;
-(id)subActionLabels;
-(id)sourceDate;
-(id)ignoreAction;
-(id)action;
-(BOOL)matchesContext:(id)context;
-(int)defaultActionType;
-(id)categoryImage;
-(id)subTitle;
-(id)title;
-(void)updateBulletinToInstance:(id)instance;
-(void)dealloc;
-(id)initWithBulletin:(id)bulletin feed:(unsigned)feed;
@end

