/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBStarkBannerTargetObserver <NSObject>
-(void)starkBannerTarget:(id)target didChangeContextWithDismissReason:(int)dismissReason;
@end

