/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBStarkNotificationViewControllerDelegate <NSObject>
-(void)notificationViewController:(id)controller stateDidChangeFrom:(int)state;
@end

