/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBSUICarDisplayNowPlayingHostInterface.h"
#import "SBSUICarDisplayNowPlayingInterface.h"

@protocol SBStarkNowPlayingServiceDelegate;

__attribute__((visibility("hidden")))
@interface SBStarkNowPlayingService : XXUnknownSuperclass <SBSUICarDisplayNowPlayingHostInterface, SBSUICarDisplayNowPlayingInterface> {
	id<SBStarkNowPlayingServiceDelegate> _delegate;
}
@property(assign, nonatomic) id<SBStarkNowPlayingServiceDelegate> delegate;
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)switchToState:(id)state;
-(void)viewServiceDidTerminateWithError:(id)viewService;
@end

