/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@class SBApplication, SBAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAppToImpersonatedAppWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction {
	SBAlert* _activatingAlert;
	BOOL _animatedAppDeactivation;
	SBApplication* _mainScreenAppThatWillBeActivated;
	id _mainScreenAppThatWillBeActivatedObserver;
}
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(BOOL)selfStarkAlertDidActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(BOOL)selfStarkAlertWillActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(id)_newAnimationFromAppToNowPlaying;
-(id)_newAnimationFromLauncherToApp;
-(id)_newAnimationFromAppToApp;
-(int)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_finishCommit;
-(void)_doCommit;
-(id)swizzledToDisplayIfNecessary;
-(void)_noteWillActivateApplicationOnMainScreen:(id)_note underLock:(BOOL)lock;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

