/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBStarkLockOutView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	float _titleAscender;
	float _titleDescender;
	UIImageView* _imageView;
	CGSize _imageSize;
	UILabel* _messageLabel;
	float _messageAscender;
	float _messageDescender;
	NSArray* _baselineSeparations;
}
@property(readonly, assign, nonatomic) UIImageView* imageView;
@property(readonly, assign, nonatomic) UILabel* messageLabel;
@property(readonly, assign, nonatomic) UILabel* titleLabel;
-(void)_sizeMessageToFitInFrame:(CGRect)frame;
-(id)_messageFontOfSize:(float)size;
-(void)_sizeTitleToFitInFrame:(CGRect)frame;
-(id)_titleFontOfSize:(float)size;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame title:(id)title image:(id)image message:(id)message baselineSeparations:(id)separations;
@end

