/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkToAppWorkspaceTransaction.h"
#import "SBUIAnimationControllerDelegate.h"

@class SBUIAnimationController, BKSApplicationActivationAssertion, SBApplication;

__attribute__((visibility("hidden")))
@interface SBStarkAppToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerDelegate> {
	SBApplication* _fromApp;
	SBUIAnimationController* _animationController;
	BKSApplicationActivationAssertion* _suspendingAppAssertion;
	BOOL _animatedActivation;
	BOOL _animatedDeactivation;
}
@property(readonly, assign, nonatomic) SBApplication* fromApp;
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(id)_newAnimationFromLauncherToNowPlaying;
-(id)_newAnimationFromNowPlayingToLauncher;
-(id)_newAnimationFromNowPlayingToNowPlaying;
-(id)_newAnimationFromNowPlayingToApp;
-(id)_newAnimationFromLauncherToApp;
-(id)_newAnimationFromAppToLauncher;
-(id)_newAnimationFromAppToNowPlaying;
-(id)_newAnimationFromAppToApp;
-(void)_doCommit;
-(id)_animation;
-(void)_handleAppDidNotChange;
-(id)_defaultAnimationFactory;
-(id)_setupAnimationFrom:(id)from to:(id)to;
-(id)swizzledToDisplayIfNecessary;
-(void)_transactionComplete;
-(void)_interruptWithReason:(int)reason;
-(BOOL)_canBeInterrupted;
-(void)_endAnimation;
-(BOOL)selfStarkAlertDidDeactivate:(id)selfStarkAlert;
-(BOOL)selfAlertDidDeactivate:(id)selfAlert;
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(BOOL)selfApplicationActivated:(id)activated;
-(BOOL)selfApplicationDidFinishLaunching:(id)selfApplication withInfo:(id)info;
-(BOOL)selfApplicationDidBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(BOOL)selfApplicationWillBecomeReceiver:(id)selfApplication fromApplication:(id)application;
-(void)_commit;
-(void)_beginAnimation;
-(int)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_noteWillActivateApplicationOnMainScreen:(id)_note underLock:(BOOL)lock;
-(id)debugDescription;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

