/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol SBSystemLocalNotificationAlertDelegate
-(void)systemLocalNotificationAlertShouldLaunch:(id)systemLocalNotificationAlert;
@optional
-(void)systemLocalNotificationAlertShouldSnooze:(id)systemLocalNotificationAlert;
@end

