/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertView.h"


__attribute__((visibility("hidden")))
@interface SBTestStarkAlertView : SBAlertView {
}
-(void)alertDisplayWillBecomeVisible;
@end

