/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBWidgetSectionInfo.h"

@class SBItemInfoLayoutCache;

__attribute__((visibility("hidden")))
@interface SBTodayWidgetSectionInfo : SBBBWidgetSectionInfo {
	SBItemInfoLayoutCache* _layoutCache;
	BOOL _isAfterTodaySection;
}
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(BOOL)_isPreviousSectionTodaySection:(id)section;
-(void)invalidateCachedLayoutData;
-(Class)reusableViewClass;
-(id)representedListSection;
-(void)dealloc;
@end

