/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBTodayTableDateHeaderFactory : XXUnknownSuperclass {
}
+(id)languagesSupportingDateOrdinals;
-(id)dateHeaderWithDate:(id)date locale:(id)locale singleLine:(BOOL)line;
-(id)dateFormatForLocale:(id)locale singleLine:(BOOL)line;
-(BOOL)isDateOrdinalSupportedForLocale:(id)locale;
@end

