/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"


__attribute__((visibility("hidden")))
@interface SBTodaySectionInfo : SBBBSectionInfo {
}
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(Class)reusableViewClass;
-(id)identifier;
@end

