/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"

@class SBItemInfoLayoutCache;

__attribute__((visibility("hidden")))
@interface SBTomorrowSectionInfo : SBBBSectionInfo {
	SBItemInfoLayoutCache* _layoutCache;
}
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode;
-(void)invalidateCachedLayoutData;
-(Class)reusableViewClass;
-(id)identifier;
-(void)dealloc;
@end

