/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface SBTodayTableHeaderView : XXUnknownSuperclass {
	UILabel* _dateLabel;
	BOOL _isContentValid;
	CGRect _calculatedDateLabelFrame;
	BOOL _achievedPreferredDateLabelLayout;
	CGSize _sizeThatFitsCalculatedDateLabelFrame;
	int _layoutMode;
}
@property(assign, nonatomic) int layoutMode;
+(id)defaultFont;
+(id)defaultTextColor;
+(id)defaultBackgroundColor;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(BOOL)_isCachedSizeThatFitsValidForSize:(CGSize)size;
-(CGRect)dateLabelFrameForBounds:(CGRect)bounds force:(BOOL)force;
-(BOOL)_dateLabelNeedsLayoutForSize:(CGSize)size;
-(float)_dateLabelWidthForSize:(CGSize)size layoutMode:(int)mode;
-(id)dateHeaderAttributedStringOnSingleLine:(BOOL)line;
-(id)dateHeaderOnSingleLine:(BOOL)line;
-(void)invalidateContent;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

