/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBTodayTableDateHeader : XXUnknownSuperclass {
	BOOL _shouldSuperscriptOrdinal;
	NSString* _dateString;
	NSRange _ordinalRange;
}
@property(readonly, assign) BOOL shouldSuperscriptOrdinal;
@property(readonly, assign) NSRange ordinalRange;
@property(readonly, assign) NSString* dateString;
+(id)dateHeaderWithDate:(id)date locale:(id)locale singleLine:(BOOL)line;
-(void)dealloc;
-(id)initWithDateString:(id)dateString ordinalRange:(NSRange)range shouldSuperscriptOrdinal:(BOOL)ordinal;
@end

