/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "UIActionSheetDelegatePrivate.h"
#import "SBAlertView.h"

@class UIImage, UIView, UIActionSheet, TPLCDView;

__attribute__((visibility("hidden")))
@interface SBTTYPromptAlertDisplay : SBAlertView <UIActionSheetDelegatePrivate> {
	UIView* _containerView;
	UIActionSheet* _voiceAndTTYSheet;
	TPLCDView* _promptView;
	BOOL _didAnimateIn;
	UIImage* _calleeImage;
	BOOL _imageSetupDone;
}
-(id)thumbnailImage;
-(void)computeImageInformation;
-(void)_ignore;
-(void)_chooseTTYMode;
-(void)_chooseVoiceMode;
-(void)_makeCall;
-(BOOL)_actionSheet:(id)sheet shouldDismissForButtonAtIndex:(int)index;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)startAnimatingIn;
-(void)dismiss;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isSupportedInterfaceOrientation:(int)orientation;
-(float)_lcdYOffset;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

