/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIControlCenterControlObserver <NSObject>
@optional
-(void)controlConfigurationDidChangeForState:(int)controlConfiguration;
-(void)controlAppearanceDidChangeForState:(int)controlAppearance;
@end

