/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationDosidoTransitionController.h"

@class SBLockScreenViewControllerBase;

__attribute__((visibility("hidden")))
@interface SBUIAnimationLockScreenCameraToApp : SBUIAnimationDosidoTransitionController {
	SBLockScreenViewControllerBase* _lockscreenVC;
}
-(void)_cleanupAnimation;
-(void)hideRealFromView;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingLockscreen:(id)lockscreen;
@end

