/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIControlCenterControlObserver.h"


@protocol SBUIControlCenterControl <SBUIControlCenterControlObserver>
@end

