/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationFadeAlertToPhone.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationSnapAlertToPhone : SBUIAnimationFadeAlertToPhone {
}
-(void)_cleanupAnimation;
-(BOOL)_shouldAnimateWallpaper;
-(void)_startAnimation;
@end

