/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkZoomDownAppToHomeAnimation.h"


__attribute__((visibility("hidden")))
@interface SBUIStarkZoomDownNowPlayingToHomeAnimation : SBUIStarkZoomDownAppToHomeAnimation {
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(BOOL)_animationShouldStart;
-(id)_viewToAnimate;
@end

