/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkStartupToAppAnimation.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface SBUIStarkStartupToNowPlaying : SBUIStarkStartupToAppAnimation {
	NSNumber* _activated;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(BOOL)_animationShouldStart;
-(id)_getTransitionWindow;
-(id)_createViewToAnimate;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp fromLockoutView:(id)lockoutView starkScreenController:(id)controller;
@end

