/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBDosidoAnimator, UIView, SBUIAnimationWindow;

__attribute__((visibility("hidden")))
@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController {
	SBUIAnimationWindow* _transitionWindow;
	UIView* _fromAppContextHostView;
	UIView* _fromView;
	UIView* _toView;
	SBDosidoAnimator* _dosidoAnimator;
	int _fromOrientation;
	BOOL _fromNC;
	BOOL _fromCC;
	BOOL _fromAssistant;
	BOOL _requiresHostView;
}
-(void)_performDosido;
-(void)_kickOffAnimation;
-(void)_setFromView:(id)view;
-(void)captureFlagsForActivatingDisplay:(id)activatingDisplay;
-(void)hideRealFromView;
-(void)setToView:(id)view;
-(int)orientationAtLaunch;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)_setHidden:(BOOL)hidden;
-(id)_animationProgressDependency;
-(BOOL)_animationShouldStart;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingApp:(id)app;
-(id)_getTransitionWindow;
@end

