/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkScreenAnimationController.h"


__attribute__((visibility("hidden")))
@interface SBUIStarkNullAnimationController : SBUIStarkScreenAnimationController {
}
-(BOOL)_isNullAnimation;
@end

