/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class SBLockToAppStatusBarAnimator, SBAlert;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeAlertToSpringBoard : SBUIMainScreenAnimationController {
	SBAlert* _fromAlert;
	SBLockToAppStatusBarAnimator* _statusBarAnimator;
}
-(void)_startAnimation;
-(void)dealloc;
-(id)initFromAlert:(id)alert;
@end

