/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomDownAppToHome.h"

@class SBIconAnimator, SBLockScreenViewController, SBLockToAppStatusBarAnimator;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomDownLockScreenToHome : SBUIAnimationZoomDownAppToHome {
	SBLockScreenViewController* _lockScreenViewController;
	SBLockToAppStatusBarAnimator* _statusBarAnimator;
	SBIconAnimator* _iconAnimator;
}
-(BOOL)_shouldTakeActivationAssertionForDeactivatingApp;
-(void)animateZoomWithCompletion:(id)completion;
-(void)cleanupZoom;
-(void)prepareZoom;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithLockScreenViewController:(id)lockScreenViewController;
@end

