/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomUpApp.h"

@class SBAlertManager, SBAlert;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromAlert : SBUIAnimationZoomUpApp {
	SBAlertManager* _alertManager;
	SBAlert* _alert;
}
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(double)animationDelay;
-(double)animationDuration;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp deactivatingAlert:(id)alert alertManager:(id)manager;
@end

