/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIControlCenterButtonDelegate <NSObject>
-(void)buttonTapped:(id)tapped;
@optional
-(void)button:(id)button didChangeState:(int)state;
@end

