/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIPasscodeLockViewDelegate.h"


@protocol SBUIPasscodeLockViewDelegate_Internal <SBUIPasscodeLockViewDelegate>
@optional
-(void)passcodeLockViewKeypadKeyUp:(id)up;
-(void)passcodeLockViewKeypadKeyDown:(id)down;
@end

