/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconAnimatorDelegate.h"
#import "SBUIStarkScreenAnimationController.h"

@class SBIconAnimator, UIView, SBAlert;

__attribute__((visibility("hidden")))
@interface SBUIStarkZoomDownAppToHomeAnimation : SBUIStarkScreenAnimationController <SBIconAnimatorDelegate> {
	UIView* _viewToAnimate;
	SBIconAnimator* _iconAnimator;
	SBAlert* _alertImpersonator;
	BOOL _animationFinished;
	BOOL _fromAssistant;
}
-(void)iconAnimatorWasInvalidated:(id)invalidated;
-(void)_noteZoomDidFinish;
-(void)_applicationDependencyStateChanged;
-(void)_cleanupHosting;
-(void)_animateZoomWithCompletion:(id)completion;
-(void)_prepareZoom;
-(double)_animationDuration;
-(double)_animationDelay;
-(void)_noteDependencyDidInvalidate;
-(id)_viewToAnimate;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithDeactivatingApp:(id)deactivatingApp alertImpersonator:(id)impersonator starkScreenController:(id)controller;
@end

