/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkZoomUpAppFromHomeAnimation.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface SBUIStarkZoomUpNowPlayingFromHomeAnimation : SBUIStarkZoomUpAppFromHomeAnimation {
	NSNumber* _activated;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(BOOL)_animationShouldStart;
-(id)_viewToAnimate;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp alertImpersonator:(id)impersonator starkScreenController:(id)controller;
@end

