/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBIconAnimatorDelegate.h"
#import "SBUIAnimationZoomUpApp.h"

@class SBIconAnimator;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromHome : SBUIAnimationZoomUpApp <SBIconAnimatorDelegate> {
	SBIconAnimator* _iconAnimator;
}
-(void)iconAnimatorWasInvalidated:(id)invalidated;
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(void)dealloc;
@end

