/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomDownApp.h"

@class SBIconAnimator;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomDownAppToHome : SBUIAnimationZoomDownApp {
	SBIconAnimator* _iconAnimator;
}
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(BOOL)_shouldUpdateStatusBarOnContentRestore;
-(void)prepareZoom;
-(void)dealloc;
@end

