/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkStartupAnimation.h"
#import "SBWindowContextHostManagerObserver.h"

@class UIStatusBar, SBWindowContextHostManager, UIView;

__attribute__((visibility("hidden")))
@interface SBUIStarkStartupToAppAnimation : SBUIStarkStartupAnimation <SBWindowContextHostManagerObserver> {
	SBWindowContextHostManager* _contextHostManager;
	UIView* _viewToAnimate;
	UIStatusBar* _fakeStatusBar;
	BOOL _finished;
}
-(void)windowContextHostManagerDidInvalidate:(id)windowContextHostManager;
-(void)windowContextHostManagerContextsDidChange:(id)windowContextHostManagerContexts;
-(void)_animationWatchdogFired;
-(void)_cancelAnimationWatchdog;
-(void)_scheduleAnimationWatchdog;
-(void)_finishedAnimation:(BOOL)animation;
-(void)_cleanupAnimation;
-(void)_cancelAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(id)_getTransitionWindow;
-(void)_applicationDependencyStateChanged;
-(BOOL)_animationShouldStart;
-(id)_animationProgressDependency;
-(id)_createViewToAnimate;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp fromLockoutView:(id)lockoutView starkScreenController:(id)controller;
@end

