/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIBiometricEventObserver <NSObject>
-(void)biometricEventMonitor:(id)monitor handleBiometricEvent:(unsigned)event;
@end

