/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationPhoneToLockScreenBase.h"

@class SBDisableUnlockAssertion;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadePhoneToLockScreen : SBUIAnimationPhoneToLockScreenBase {
	SBDisableUnlockAssertion* _disableUnlockAssertion;
	int _launchingOrientation;
}
-(void)_showLockStatusBar:(id)bar;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
@end

