/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBCenterZoomSettings.h"


__attribute__((visibility("hidden")))
@interface SBUnlockSettings : SBCenterZoomSettings {
}
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

