/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUnlockActionHandler <NSObject>
-(void)unlockUIWithActionContext:(id)actionContext;
@end

