/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBApplicationIcon.h"


__attribute__((visibility("hidden")))
@interface SBUserInstalledApplicationIcon : SBApplicationIcon {
}
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
-(id)uninstallAlertBodyForAppWithDocumentsInCloud;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
-(id)uninstallAlertTitleForAppWithDocumentsInCloud;
-(id)uninstallAlertTitle;
-(id)ratingsAlertRateButtonTitle;
-(id)ratingsAlertSkipTitle;
-(id)ratingsAlertBody;
-(id)ratingsAlertTitle;
@end

