/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBVibrantBannerView <NSObject>
+(id)defaultColorForElement:(int)element;
-(void)setColor:(id)color forElement:(int)element;
-(id)colorForElement:(int)element;
@end

