/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBVoiceControlAlert : SBAlert {
	struct {
		unsigned shouldBeActivated : 1;
		unsigned isReadyToBeActivated : 1;
		unsigned hasBeenActivated : 1;
	} _voiceControlFlags;
	BOOL _expectsFaceContact;
	BOOL _expectsFaceContactInLandscape;
}
@property(assign) BOOL expectsFaceContact;
@property(readonly, assign) BOOL expectsFaceContactInLandscape;
+(void)setNextRecognitionAudioInputPaths:(id)paths;
+(void)bluetoothDeviceTerminatedVoiceControl:(id)control;
+(void)bluetoothDeviceRequestedVoiceControl:(id)control;
+(BOOL)resetVoiceControlIfNecessary:(BOOL)necessary;
+(BOOL)shouldEnterVoiceControl;
+(void)unregisterForAlerts;
+(void)registerForAlerts;
+(id)pendingOrActiveAlert;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(double)autoDimTime;
-(BOOL)handleMenuButtonTap;
-(void)handleHeadsetButtonUpFromActivation:(BOOL)activation;
-(void)dealloc;
-(void)cancel;
-(void)cancelIfNotActivated;
-(void)activateWhenReady;
-(id)initFromMenuButton;
-(void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
-(id)initFromWiredHeadsetButton;
-(id)init;
-(void)_setRoutingAttributesForWiredHeadset:(BOOL)wiredHeadset;
-(void)_prime;
-(void)_makeActive;
-(void)_resign;
@end

