/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBWallpaperDefaults : XXUnknownSuperclass {
}
+(id)defaults;
-(BOOL)supportsCroppingForVariant:(int)variant;
-(void)setSupportsCropping:(BOOL)cropping forLocations:(int)locations;
-(CGRect)cropRectForVariant:(int)variant;
-(void)setCropRect:(CGRect)rect forLocations:(int)locations;
-(void)resetCroppingDefaults;
-(float)zoomScaleForVariant:(int)variant;
-(void)setZoomScale:(float)scale forLocations:(int)locations;
-(void)resetZoomScaleDefaults;
-(float)parallaxFactorForVariant:(int)variant;
-(void)setParallaxFactor:(float)factor forLocations:(int)locations;
-(void)resetParallaxFactorDefaults;
-(void)setWallpaperOptions:(id)options forLocations:(int)locations;
-(void)resetDefaults;
@end

