/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"


__attribute__((visibility("hidden")))
@interface SBWallpaperStyleRecipe : XXUnknownSuperclass <SBTestRecipe> {
}
+(id)title;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

