/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconIndexNodeObserver.h"

@class SBFMappedImageCache;

__attribute__((visibility("hidden")))
@interface SBWallpaperPreviewSnapshotCache : XXUnknownSuperclass <SBIconIndexNodeObserver> {
	SBFMappedImageCache* _imageCache;
	int _invalidatedLocations;
}
-(id)_lockScreenSnapshotProvider;
-(id)_homeScreenSnapshotProvider;
-(void)_backlightFadeFinished;
-(void)_modelDidLayout;
-(void)_modelWillLayout;
-(void)node:(id)node didRemoveContainedNodeIdentifiers:(id)identifiers;
-(void)node:(id)node didAddContainedNodeIdentifiers:(id)identifiers;
-(void)regenerateSnapshotsForLocations:(int)locations withCompletion:(id)completion;
-(id)homeScreenSnapshot;
-(id)lockScreenSnapshot;
-(void)invalidateSnapshotsForLocations:(int)locations;
-(void)dealloc;
-(id)initWithImageCache:(id)imageCache;
@end

