/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWallpaperObserver.h"

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBWallpaperEffectSnapshotCache : XXUnknownSuperclass <SBWallpaperObserver> {
	NSMutableSet* _mappedImageKeys;
}
+(id)sharedInstance;
-(void)wallpaperWillChangeForVariant:(int)wallpaper;
-(id)snapshotForKey:(id)key withGenerationBlockIfNecessary:(id)generationBlockIfNecessary;
-(void)dealloc;
-(id)init;
@end

