/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBFLegibilitySettingsProvider.h"
#import "SBWallpaperObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class _UILegibilitySettings;
@protocol SBFLegibilitySettingsProviderDelegate;

__attribute__((visibility("hidden")))
@interface SBWallpaperLegibilitySettingsProvider : XXUnknownSuperclass <SBWallpaperObserver, SBFLegibilitySettingsProvider> {
	id<SBFLegibilitySettingsProviderDelegate> _delegate;
	int _variant;
}
@property(readonly, assign, nonatomic) _UILegibilitySettings* legibilitySettings;
@property(assign, nonatomic) id<SBFLegibilitySettingsProviderDelegate> delegate;
-(void)wallpaperLegibilitySettingsDidChange:(id)wallpaperLegibilitySettings forVariant:(int)variant;
-(void)wallpaperDidChangeForVariant:(int)wallpaper;
-(void)dealloc;
-(id)initWithVariant:(int)variant;
@end

