/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBWhiteBackdropSettings : XXUnknownSuperclass {
}
-(float)blurRadius;
-(id)combinedTintColor;
@end

