/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBWindowContextHostManagerObserver <NSObject>
@optional
-(void)windowContextHostManagerDidInvalidate:(id)windowContextHostManager;
-(void)windowContextHostManagerDidResumeHosting:(id)windowContextHostManager;
-(void)windowContextHostManagerDidSuspendHosting:(id)windowContextHostManager;
-(void)windowContextHostManagerContextsDidChange:(id)windowContextHostManagerContexts;
@end

