/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBRecycledViewsContainer;

__attribute__((visibility("hidden")))
@interface SBWindow : XXUnknownSuperclass {
	SBRecycledViewsContainer* _recycledViewsContainerView;
	int _jailBehavior;
}
@property(readonly, assign, nonatomic) UIEdgeInsets jailInsets;
+(CGRect)_actualBoundsForScreen:(id)screen withJailBehavior:(int)jailBehavior;
+(UIEdgeInsets)_jailInsetsForScreen:(id)screen;
-(BOOL)_isClippedByScreenJail;
-(BOOL)_isConstrainedByScreenJail;
-(void)setAlpha:(float)alpha;
-(id)recycledViewsContainer;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithScreen:(id)screen jailBehavior:(int)behavior;
-(id)initWithScreen:(id)screen;
-(void)setAlphaAndObeyBecauseIAmTheWindowManager:(float)manager;
@end

