/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBWindowContextHostViewDelegate <NSObject>
-(void)windowContextHostViewHostedContextsDidChange:(id)windowContextHostViewHostedContexts;
@end

