/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWindowContextManagerObserver.h"

@class NSSet, NSMutableOrderedSet, SBWindowContextManager, NSMutableSet, SBWindowContextHostViewContentLayerDelegate, NSMutableArray, CALayer, UIScreen;
@protocol SBWindowContextHostViewDelegate;

__attribute__((visibility("hidden")))
@interface SBWindowContextHostView : XXUnknownSuperclass <SBWindowContextManagerObserver> {
	UIScreen* _screen;
	CALayer* _contentLayer;
	id<SBWindowContextHostViewDelegate> _delegate;
	SBWindowContextManager* _contextManager;
	SBWindowContextHostViewContentLayerDelegate* _contentLayerDelegate;
	int _jailBehavior;
	NSMutableSet* _hiddenContexts;
	NSMutableOrderedSet* _contexts;
	NSMutableArray* _layerHosts;
}
@property(copy, nonatomic) NSSet* hiddenContexts;
@property(retain, nonatomic) SBWindowContextManager* contextManager;
@property(assign, nonatomic) id<SBWindowContextHostViewDelegate> delegate;
@property(readonly, assign, nonatomic) UIScreen* screen;
-(void)windowContextManager:(id)manager didRepositionContext:(id)context from:(unsigned)from to:(unsigned)to forScreen:(id)screen;
-(id)description;
-(void)_noteHostingStatusChanged;
-(id)window;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(CGRect)contentFrame;
-(BOOL)hasContent;
-(BOOL)isHosting;
-(void)_adjustLayerFrameAndTransform:(id)transform;
-(void)dealloc;
-(id)init;
-(id)initWithScreen:(id)screen jailBehavior:(int)behavior;
@end

