/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBWindowContextHostViewContentLayerDelegate : XXUnknownSuperclass {
}
-(id)actionForLayer:(id)layer forKey:(id)key;
@end

