/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSRecursiveLock, NSString, NSObject;
@protocol OS_dispatch_source;

__attribute__((visibility("hidden")))
@interface SBWiFiManager : XXUnknownSuperclass {
	NSRecursiveLock* _lock;
	void* _manager;
	void* _device;
	NSString* _deviceInterfaceName;
	BOOL _devicePresent;
	void* _currentNetwork;
	void* _previousNetwork;
	BOOL _currentNetworkHasBeenSet;
	BOOL _currentNetworkIsIOSHotspot;
	BOOL _currentNetworkIsIOSHotspotHasBeenSet;
	BOOL _powered;
	BOOL _poweredHasBeenSet;
	int _rssiThreshold;
	int _signalStrengthBars;
	int _signalStrengthRSSI;
	BOOL _signalStrengthHasBeenSet;
	SCDynamicStoreRef _SCDynamicStoreNetworkState;
	NSObject<OS_dispatch_source>* _SCUpdateTimeoutSource;
	void* _primaryInterface;
	BOOL _primaryInterfaceHasBeenSet;
	BOOL _isPrimaryInterface;
	BOOL _isPrimaryInterfaceChanging;
}
@property(assign) BOOL wiFiEnabled;
@property(assign, getter=isPowered) BOOL powered;
@property(readonly, assign) BOOL devicePresent;
@property(readonly, assign) int signalStrengthBars;
@property(readonly, assign) int signalStrengthRSSI;
@property(readonly, assign) BOOL isPrimaryInterface;
+(id)sharedInstance;
-(void)_primaryInterfaceChanged:(BOOL)changed;
-(id)_wifiInterface;
-(void)resetSettings;
-(id)knownNetworks;
-(void)updateSignalStrength;
-(void)updateSignalStrengthFromRawRSSI:(int)rawRSSI andScaledRSSI:(float)rssi;
-(id)currentNetworkName;
-(BOOL)_cachedIsAssociated;
-(BOOL)isAssociatedToIOSHotspot;
-(BOOL)isAssociated;
-(void)_updateCurrentNetwork;
-(void)_updateWiFiDevice:(id)device;
-(void)_linkDidChange;
-(void)_powerStateDidChange;
-(void)_updateWiFiState;
-(void*)_manager;
-(void)_setWiFiDevice:(void*)device;
-(void)updateDevicePresence;
-(BOOL)wifiSupported;
-(id)init;
@end

