/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransactionDelegate.h"


@protocol SBWorkspaceTransactionGroupDelegate <SBWorkspaceTransactionDelegate>
@optional
-(void)transactionGroup:(id)group childTransactionDidFinish:(id)childTransaction success:(BOOL)success;
@end

