/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBWorkspaceEventQueue, NSString;

__attribute__((visibility("hidden")))
@interface SBWorkspaceEventQueueLockAssertion : XXUnknownSuperclass {
	SBWorkspaceEventQueue* _eventQueue;
	NSString* _reason;
}
@property(readonly, retain) NSString* reason;
-(id)description;
-(void)dealloc;
-(id)initWithWorkspaceEventQueue:(id)workspaceEventQueue reason:(id)reason;
@end

