/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SFAirDropDiscoveryControllerDelegate <NSObject>
-(void)discoveryControllerVisibilityDidChange:(id)discoveryControllerVisibility;
-(void)discoveryControllerSettingsDidChange:(id)discoveryControllerSettings;
@end

