/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"


@protocol UIActionSheetDelegatePrivate <UIActionSheetDelegate>
@optional
-(BOOL)_actionSheet:(id)sheet shouldDismissForButtonAtIndex:(int)index;
@end

