/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface UIResizableView : XXUnknownSuperclass {
}
-(CGSize)sizeThatFits:(CGSize)fits;
@end

