/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol UIStatusBarStateProvider <NSObject>
-(void)getStatusBarData:(XXStruct_8iXKhD*)data;
-(void)removeStatusBarStateObserver:(id)observer;
-(void)addStatusBarStateObserver:(id)observer;
@optional
-(id)doubleHeightStatusStringForStyle:(int)style;
@end

