/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSObject.h"


@protocol UIStatusBarStateObserver <NSObject>
-(void)statusBarStateProvider:(id)provider didPostStatusBarData:(const XXStruct_8iXKhD*)data withActions:(int)actions;
@optional
-(void)statusBarStateProvider:(id)provider didChangeDoubleHeightStatusStringForStyle:(int)style;
@end

